{
  "hash": "3ecf8247b1417c00f8376f33a902267c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Philadelphia Fire Inspection Risk Model\"\nsubtitle: \"Predicting Building Inspection Failures Using Logistic Regression\"\nauthor: \"Liz, Arzoo and Shaurya\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contents\"\n    code-fold: true\n    code-summary: \"Show code\"\n    theme: cosmo\n    embed-resources: true\n    fig-width: 9\n    fig-height: 6\nexecute:\n  warning: false\n  message: false\n  echo: true\n---\n\n# Executive Summary\n\nPhiladelphia's buildings don't get inspected unless someone complains. With fewer than 45 inspectors covering the entire city, the Department of Licenses and Inspections relies almost entirely on resident complaints to trigger fire safety checks, meaning buildings in communities that are less likely to report problems are less likely to get inspected, regardless of actual conditions on the ground (Pew Charitable Trusts, 2021).\n\nThis report presents a predictive model designed to give the city a better starting point. Using publicly available data on past inspection outcomes, property characteristics, neighbourhood demographics, 311 complaint activity, and the physical location of each building relative to others in the city, the model assigns each property a probability of failing a fire safety inspection. The goal is not to replace inspectors or automate enforcement decisions, it is to help the city direct its limited inspection capacity toward the buildings where failure is most likely, before a complaint ever arrives.\n\nThe model correctly identifies approximately 8 in 10 buildings that go on to fail inspection, while clearing roughly 6 in 10 safe buildings from the high-priority queue. Buildings the model flags as low risk are correct 99% of the time. In practice, this means the city could use the model to generate a ranked list of properties by risk level—inspecting the highest-risk buildings first rather than waiting for residents to report problems.\n\nThis document walks through every step of how that model was built: where the data came from, how it was cleaned and joined, what features were constructed and why, how the model was developed and validated, and where it falls short. The limitations and safeguards should be acknowledged and should be incorporated into the city's use of the model. As the model learns from a complaint-driven system and cannot fully escape its biases ,and they are documented here in full.\n\nThe goal is a **decision-support triage tool** that helps the city prioritize which buildings to inspect, not a replacement for inspector judgment.\n\n------------------------------------------------------------------------\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(sf)\nlibrary(ggplot2)\nlibrary(tidyverse)\nlibrary(lubridate)\nlibrary(here)\nlibrary(tidygeocoder)\nlibrary(readxl)\nlibrary(caret)\nlibrary(pROC)\nlibrary(spdep)\nlibrary(themis)\nlibrary(nngeo)\nlibrary(knitr)\nlibrary(kableExtra)\n\noptions(tigris_use_cache = TRUE)\nknitr::opts_knit$set(root.dir = here::here(\"Labs\", \"Final_Challenge\"))\n```\n:::\n\n\n## Plot Themes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotTheme <- theme_minimal() +\n  theme(\n    plot.title       = element_text(size = 14, face = \"bold\"),\n    plot.subtitle    = element_text(size = 10),\n    plot.caption     = element_text(size = 8),\n    axis.text.x      = element_text(size = 10, angle = 45, hjust = 1),\n    axis.text.y      = element_text(size = 10),\n    axis.title       = element_text(size = 11, face = \"bold\"),\n    panel.grid.major = element_line(colour = \"#D0D0D0\", linewidth = 0.2),\n    panel.grid.minor = element_blank(),\n    axis.ticks       = element_blank(),\n    legend.position  = \"right\"\n  )\n\nmapTheme <- theme_void() +\n  theme(\n    plot.title        = element_text(size = 14, face = \"bold\"),\n    plot.subtitle     = element_text(size = 10),\n    plot.caption      = element_text(size = 8),\n    legend.position   = \"right\",\n    plot.margin       = margin(1, 1, 1, 1, \"cm\"),\n    legend.key.height = unit(1, \"cm\"),\n    legend.key.width  = unit(0.2, \"cm\")\n  )\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Data Loading\n\n## Data Sources\n\nThe following table summarises all data sources used in the analysis, what each contributes, and their vintage.\n\n| Source | Contribution |\n|------------------------------------|------------------------------------|\n| L&I Building Certifications (OpenDataPhilly) | Outcome variable: pass/fail; certification type fixed effects |\n| OPA Property Data (OpenDataPhilly) | Market value, building age, property count by land use type |\n| Philadelphia 311 Service Requests (OpenDataPhilly) | Fire Department complaint volume by block group |\n| ACS 5-Year Estimates (Census Bureau) | Median income, vacancy rate, renter occupancy, rent burden, at the block group level |\n| SEPTA Transit Stops (OpenDataPhilly) | Distance to nearest transit stop |\n| L&I Code Violations (OpenDataPhilly) | Nearby violation count within 500m buffer |\n| Philadelphia City Limits (OpenDataPhilly) | Boundary for geocoding clip |\n\n## Geographic Boundaries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphiladelphia  <- counties(state = \"PA\")\nphl_tracts    <- tracts(state = \"PA\", county = \"Philadelphia\")\nblocks        <- blocks(state = \"PA\", county = \"Philadelphia\")\nblock_groups  <- block_groups(state = \"PA\", county = \"Philadelphia\") %>%\n  st_transform(crs = 4326)\n```\n:::\n\n\n## Raw Inspection Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections <- read.csv(\"data/BUILDING_CERTS.csv\")\n\n\ninspections <- inspections %>%\n  mutate(\n    inspectiondate = as.Date(inspectiondate),\n    year           = year(inspectiondate),\n    month          = month(inspectiondate, label = TRUE),\n    quarter        = quarter(inspectiondate)\n  )\n\ncat(\"Total inspections:\", nrow(inspections), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal inspections: 108805 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Date range:\", min(inspections$inspectiondate, na.rm = TRUE),\n    \"to\", max(inspections$inspectiondate, na.rm = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDate range: 11316 to 20551 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Unique addresses:\", length(unique(inspections$address)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnique addresses: 23752 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Missing inspection results:\", sum(is.na(inspections$inspectionresult)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing inspection results: 0 \n```\n\n\n:::\n:::\n\n\n## 311 Service Requests\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphl_311 <- read.csv(\"data/311reqs.csv\")\n```\n:::\n\n\n## ACS Demographics (Block Group)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphl_census <- get_acs(\n  geography = \"block group\",\n  variables = c(\n    \"B19013_001\",  # Median household income\n    \"B25002_002\",  # Occupied housing units\n    \"B25002_003\",  # Vacant housing units\n    \"B25002_001\",  # Total housing units\n    \"B25003_001\",  # Total occupied housing units\n    \"B25003_002\",  # Owner occupied\n    \"B25003_003\",  # Renter occupied\n    \"B01003_001\",  # Total population\n    \"B25071_001\"   # Rent burden\n  ),\n  state   = \"PA\",\n  county  = \"Philadelphia\",\n  year    = 2022,\n  geometry = TRUE,\n  output  = \"wide\"\n) %>%\n  rename(\n    Med_Inc         = B19013_001E,\n    Occupied_Units  = B25002_002E,\n    Vacant_Units    = B25002_003E,\n    Total_Units     = B25002_001E,\n    Total_Occupied  = B25003_001E,\n    Owner_Occupied  = B25003_002E,\n    Renter_Occupied = B25003_003E,\n    Total_Pop       = B01003_001E,\n    Rent_Burden     = B25071_001E\n  ) %>%\n  mutate(\n    Vacancy_Rate        = (Vacant_Units / Total_Units) * 100,\n    Pct_Renter_Occupied = (Renter_Occupied / Total_Occupied) * 100,\n    Pct_Owner_Occupied  = (Owner_Occupied / Total_Occupied) * 100\n  ) %>%\n  select(\n    GEOID, NAME, geometry,\n    Med_Inc, Total_Pop,\n    Vacancy_Rate, Vacant_Units, Total_Units,\n    Pct_Renter_Occupied, Pct_Owner_Occupied,\n    Rent_Burden\n  ) %>%\n  st_transform(crs = 4326)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Exploratory Analysis\n\nBefore any filtering or cleaning decisions are made, we explore the full raw inspection dataset to understand its structure, distributions, and data quality issues. This EDA informs the subsequent decisions around temporal scope, outcome variable definition, and certification type exclusions.\n\n## Inspection Result Distribution\n\nCertified and Safe outcomes account for the large majority of inspections. Deficient and Unsafe outcomes together represent approximately 5% of the total. Safe with Repair—inspections that passed with conditions—constitutes a small additional share. This distribution establishes the degree of class imbalance in the outcome variable that must be addressed in the modeling strategy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections %>%\n  filter(!is.na(inspectionresult)) %>%\n  count(inspectionresult) %>%\n  mutate(\n    pct              = n / sum(n),\n    inspectionresult = reorder(inspectionresult, n)\n  ) %>%\n  ggplot(aes(x = inspectionresult, y = n, fill = inspectionresult)) +\n  geom_col(show.legend = FALSE) +\n  geom_text(aes(label = scales::percent(pct, accuracy = 0.1)),\n            hjust = -0.1, size = 3.5) +\n  coord_flip() +\n  scale_fill_viridis_d(option = \"plasma\") +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.15)),\n                     labels = scales::comma) +\n  labs(\n    title    = \"Distribution of Building Inspection Results\",\n    subtitle = \"Philadelphia L&I Inspections — Full Dataset\",\n    x        = NULL,\n    y        = \"Number of Inspections\",\n    caption  = \"Source: OpenDataPhilly\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/plot-results-1.png){width=864}\n:::\n:::\n\n\n## Inspections by Certification Type\n\nAnnual Fire Alarm inspections are by far the most common certification type, followed by Suppression System and Sprinkler certifications. Several categories—Standpipe, Smoke Control, Fire Escape Report—are present in very small volumes. The distribution is highly uneven, with the three most common types accounting for the substantial majority of all inspections.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections %>%\n  filter(!is.na(buildingcerttype)) %>%\n  count(buildingcerttype) %>%\n  mutate(\n    pct              = n / sum(n),\n    buildingcerttype = reorder(buildingcerttype, n)\n  ) %>%\n  ggplot(aes(x = buildingcerttype, y = n, fill = buildingcerttype)) +\n  geom_col(show.legend = FALSE) +\n  geom_text(aes(label = scales::percent(pct, accuracy = 0.1)),\n            hjust = -0.1, size = 3.5) +\n  coord_flip() +\n  scale_fill_viridis_d(option = \"viridis\") +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.15)),\n                     labels = scales::comma) +\n  labs(\n    title    = \"Inspections by Certification Type\",\n    subtitle = \"What kinds of inspections are being conducted?\",\n    x        = NULL,\n    y        = \"Number of Inspections\",\n    caption  = \"Source: OpenDataPhilly\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/plot-certtype-1.png){width=864}\n:::\n:::\n\n\n## Inspection Results Over Time\n\nInspection volumes across all result categories show a marked drop around 2020, consistent with the suspension or reduction of in-person inspections during the COVID-19 pandemic, followed by recovery in subsequent years. A similar apparent decline is visible at the right end of the chart for 2025–2026, but this reflects an incomplete year of data rather than a genuine reduction in inspection activity. The 2024 analysis window falls within the post-recovery period and represents a full calendar year of inspection records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections %>%\n  filter(!is.na(inspectionresult), !is.na(year)) %>%\n  count(year, inspectionresult) %>%\n  ggplot(aes(x = year, y = n, color = inspectionresult)) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 2) +\n  scale_color_viridis_d(option = \"plasma\", name = \"Result\") +\n  scale_y_continuous(labels = scales::comma) +\n  labs(\n    title    = \"Inspection Results Over Time\",\n    subtitle = \"Are failure rates changing year over year?\",\n    x        = \"Year\",\n    y        = \"Number of Inspections\",\n    caption  = \"Source: OpenDataPhilly\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/plot-time-1.png){width=864}\n:::\n:::\n\n\n## Failure Rate Over Time\n\nRather than raw counts, this chart shows the annual failure rate as a share of all inspections conducted each year. This isolates genuine changes in outcome patterns from changes in inspection volume. The failure rate shows some year-to-year variation but no strong directional trend, suggesting that the 2024 analysis window captures a representative and stable period rather than an anomalous one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections %>%\n  filter(!is.na(inspectionresult), !is.na(year)) %>%\n  mutate(failed = inspectionresult == \"FAILED\") %>%\n  group_by(year) %>%\n  summarize(\n    total        = n(),\n    failures     = sum(failed, na.rm = TRUE),\n    failure_rate = failures / total\n  ) %>%\n  ggplot(aes(x = year, y = failure_rate)) +\n  geom_line(color = \"#08519c\", linewidth = 1.2) +\n  geom_point(color = \"#08519c\", size = 3) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(\n    title    = \"Inspection Failure Rate Over Time\",\n    subtitle = \"Annual share of inspections resulting in failure\",\n    x        = \"Year\",\n    y        = \"Failure Rate\",\n    caption  = \"Source: OpenDataPhilly\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/plot-failure-rate-1.png){width=864}\n:::\n:::\n\n\n## Seasonality\n\nThe stacked proportional bar chart shows the share of passing and failing inspections by month. No strong seasonal signal is visible. The failure share remains broadly consistent across months. This rules out seasonality as a major confounder and confirms that restricting the analysis to a single calendar year does not introduce a seasonal bias into the outcome variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections %>%\n  filter(!is.na(month), !is.na(inspectionresult)) %>%\n  count(month, inspectionresult) %>%\n  ggplot(aes(x = month, y = n, fill = inspectionresult)) +\n  geom_col(position = \"fill\") +\n  scale_fill_viridis_d(option = \"plasma\", name = \"Result\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(\n    title    = \"Inspection Results by Month\",\n    subtitle = \"Does seasonality affect pass/fail rates?\",\n    x        = \"Month\",\n    y        = \"Share of Inspections\",\n    caption  = \"Source: OpenDataPhilly\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/plot-seasonality-1.png){width=864}\n:::\n:::\n\n\n## Results by Certification Type\n\nThis chart shows the pass/fail breakdown within each certification type. Sprinkler certifications have a markedly higher failure rate than all other categories, a pattern that directly motivates the inclusion of certification type fixed effects in the model. Fire Alarm and Suppression certifications also show elevated failure rates relative to less complex system types. The variation across categories confirms that baseline failure probability is heavily determined by what type of system is being inspected, independent of underlying building condition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections %>%\n  filter(!is.na(inspectionresult), !is.na(buildingcerttype)) %>%\n  count(buildingcerttype, inspectionresult) %>%\n  group_by(buildingcerttype) %>%\n  mutate(pct = n / sum(n)) %>%\n  ggplot(aes(x = buildingcerttype, y = pct, fill = inspectionresult)) +\n  geom_col(position = \"stack\") +\n  coord_flip() +\n  scale_fill_viridis_d(option = \"plasma\", name = \"Result\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(\n    title    = \"Inspection Results by Certification Type\",\n    subtitle = \"Do certain inspection types fail more often?\",\n    x        = NULL,\n    y        = \"Share of Inspections\",\n    caption  = \"Source: OpenDataPhilly\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/plot-certtype-result-1.png){width=864}\n:::\n:::\n\n\n## Data Completeness\n\nThe chart documents the share of missing values for each variable in the raw inspection dataset. Core variables, inspection date, result, certification type, and address, are complete, confirming that the dataset is suitable for modeling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_summary <- inspections %>%\n  summarise(across(everything(), ~sum(is.na(.)))) %>%\n  pivot_longer(everything(),\n               names_to  = \"variable\",\n               values_to = \"n_missing\") %>%\n  mutate(\n    pct_missing = n_missing / nrow(inspections),\n    variable    = reorder(variable, pct_missing)\n  )\n\nggplot(missing_summary, aes(x = variable, y = pct_missing, fill = pct_missing)) +\n  geom_col(show.legend = FALSE) +\n  geom_text(aes(label = scales::percent(pct_missing, accuracy = 0.1)),\n            hjust = -0.1, size = 3.5) +\n  coord_flip() +\n  scale_fill_viridis_c(option = \"plasma\", direction = -1) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.15)),\n                     labels = scales::percent) +\n  labs(\n    title    = \"Data Completeness by Variable\",\n    subtitle = \"Documenting missingness before modeling\",\n    x        = NULL,\n    y        = \"% Missing\",\n    caption  = \"Source: OpenDataPhilly\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/plot-missing-1.png){width=864}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Data Preparation\n\n## Temporal Filtering\n\nThe full L&I inspection dataset spans multiple decades, but this analysis focuses exclusively on inspections conducted between January 2024 and January 2025. This decision reflects two considerations. First, recent inspections are more likely to capture current building conditions and enforcement patterns, making predictions from the model more actionable for near-term inspection prioritization. Second, restricting the temporal scope reduces noise introduced by changes in inspection practices, staffing, and reporting standards over time. Inspections from earlier periods may reflect regulatory environments or building stock conditions that no longer apply, which would reduce the relevance of those records as training data for a forward-looking risk model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspected <- inspections %>%\n  filter(\n    inspectiondate >= ymd(\"2024-01-01\") & inspectiondate <= ymd(\"2025-01-01\")\n  )\n\ncat(\"Inspections in 2024 analysis window:\", nrow(inspected), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInspections in 2024 analysis window: 27892 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rows dropped:\", nrow(inspections) - nrow(inspected), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows dropped: 80913 \n```\n\n\n:::\n:::\n\n\n## Geocoding\n\nInspection records in the L&I dataset include street addresses but no coordinates. Geocoding is therefore necessary to spatially locate each property and enable the spatial joins and distance calculations that underpin the model's key features. A two-stage geocoding strategy is used. The Census geocoder is tried first because it is purpose-built for US addresses and produces accurate results at no cost. Addresses that fail Census geocoding, typically those with non-standard formatting or missing zip codes, are passed to the ArcGIS geocoder as a fallback, which uses a broader address matching algorithm and tends to recover a large share of the remaining failures. Results from both passes are coalesced into a single coordinate pair per record.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspected <- inspected %>%\n  mutate(\n    full_address = paste(address, \"Philadelphia, PA\", zip, \"USA\")\n  )\n\n# Deduplicate addresses before geocoding to avoid redundant API calls\nunique_addresses <- inspected %>%\n  distinct(full_address)\n\n# Geocode in chunks of 10,000 via Census API\nchunks <- split(unique_addresses, ceiling(seq_len(nrow(unique_addresses)) / 10000))\n\ngeocoded <- lapply(chunks, function(chunk) {\n  chunk %>% geocode(address = full_address, method = \"census\", full_results = FALSE)\n}) %>% bind_rows()\n\ninspected <- inspected %>%\n  left_join(geocoded, by = \"full_address\")\n\n# Fall back to ArcGIS for addresses that failed Census geocoding\nfailed <- geocoded %>% filter(is.na(lat))\n\nfailed_geocoded <- failed %>%\n  geocode(address = full_address, method = \"arcgis\", full_results = FALSE)\n\ngeocoded <- geocoded %>%\n  filter(!is.na(lat)) %>%\n  bind_rows(failed_geocoded)\n\n# Re-join to get ArcGIS results into the main dataset\ninspected <- inspected %>%\n  left_join(geocoded, by = \"full_address\")\n\n# Coalesce lat/lon columns from both geocoding passes\ninspected <- inspected %>%\n  mutate(\n    lat = coalesce(lat.x, lat.y, `lat...2`, `lat...4`),\n    lon = coalesce(long.x, long.y, `long...3`, `long...5`)\n  ) %>%\n  select(-lat.x, -lat.y, -`lat...2`, -`lat...4`,\n         -long.x, -long.y, -`long...3`, -`long...5`)\n\ncat(\"Unique addresses to geocode:\", nrow(unique_addresses), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnique addresses to geocode: 15502 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Failed Census geocoding (sent to ArcGIS):\", nrow(failed), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFailed Census geocoding (sent to ArcGIS): 293 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Still missing coordinates after both passes:\", sum(is.na(inspected$lat)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStill missing coordinates after both passes: 0 \n```\n\n\n:::\n:::\n\n\n## Clipping to Philadelphia Boundary\n\nAfter geocoding, the dataset is converted to an `sf` object, reprojected to NAD83 (2011). Eleven records geocode to locations outside the Philadelphia city boundary. These are most likely the result of address ambiguities where the geocoder matched to a similarly named street in a neighbouring jurisdiction. Since the model is built exclusively on Philadelphia properties and uses Philadelphia-specific contextual features such as ACS block group demographics and 311 complaint data, records outside the boundary cannot be meaningfully modelled and are removed. The map below confirms that the retained points fall cleanly within the city boundary with no obvious geographic anomalies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspected_sf <- inspected %>%\n  st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326)\n\ninspected_NAD <- inspected_sf %>%\n  st_transform(crs = 6564)\n\nphilly <- st_read((\"data/city_boundary/City_Limits.shp\"), quiet = TRUE) %>%\n  st_transform(crs = 6564)\n\ninspected_NAD <- inspected_NAD %>%\n  st_filter(philly)\n\ncat(\"Records before boundary clip:\", nrow(inspected_sf), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecords before boundary clip: 27892 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Records after clipping to Philadelphia:\", nrow(inspected_NAD), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecords after clipping to Philadelphia: 27881 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Records dropped (outside boundary):\", nrow(inspected_sf) - nrow(inspected_NAD), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecords dropped (outside boundary): 11 \n```\n\n\n:::\n:::\n\n\nThe map shows the spatial distribution of geocoded inspection records after clipping to the Philadelphia city boundary. Points are distributed across the city with higher concentrations in denser neighbourhoods, consistent with the spatial distribution of multifamily and commercial buildings that are subject to fire safety certification requirements.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = philly, fill = \"lightgrey\", color = \"black\") +\n  geom_sf(data = inspected_NAD, color = \"steelblue\", size = 0.5, alpha = 0.5) +\n  labs(\n    title   = \"Geocoded Fire Inspections within Philadelphia\",\n    caption = \"Source: OpenDataPhilly\"\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/map-geocoded-inspections-1.png){width=864}\n:::\n:::\n\n\n## Outcome Variable Construction\n\nThe raw inspection dataset contains five distinct result categories including Certified, Safe, Safe with Repair, Deficient, and Unsafe. For the purposes of binary classification, these are collapsed into a single pass/fail indicator. Inspections recorded as Deficient or Unsafe are coded as failures (fail = 1) because both represent cases where a building did not meet the required standard at the time of inspection and require remediation or re-inspection. All other outcomes—Certified, Safe, and Safe with Repair—are coded as passes (fail = 0) as they represent buildings that met the required standard, with or without minor conditions. The chart below shows the distribution of raw result categories before this collapse, documenting the basis for the binary coding decision.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distribution of raw result categories before binary collapse\ninspected_NAD%>%\n  st_drop_geometry() %>%\n  count(inspectionresult, sort = TRUE) %>%\n  mutate(pct = n / sum(n)) %>%\n  ggplot(aes(x = reorder(inspectionresult, n), y = n, fill = inspectionresult)) +\n  geom_col(show.legend = FALSE) +\n  geom_text(aes(label = scales::percent(pct, accuracy = 0.1)),\n            hjust = -0.1, size = 3.5) +\n  coord_flip() +\n  scale_fill_viridis_d(option = \"plasma\") +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.15)),\n                     labels = scales::comma) +\n  labs(\n    title    = \"Inspection Result Categories Before Binary Collapse\",\n    subtitle = \"Deficient and Unsafe coded as fail = 1\",\n    x        = NULL,\n    y        = \"Number of Inspections\",\n    caption  = \"Source: OpenDataPhilly\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/outcome-summary-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nli_sf <- inspected_NAD %>% \n  mutate(\n    fail = ifelse(inspectionresult %in% c(\"Deficient\", \"Unsafe\"), 1, 0)\n  ) %>%\n  st_transform(26918)\n\ncat(\"Outcome distribution (fail = 1):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOutcome distribution (fail = 1):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(table(li_sf$fail))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1 \n26592  1289 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"% fail:\", round(mean(li_sf$fail) * 100, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n% fail: 4.62 \n```\n\n\n:::\n:::\n\n\n## Certification Type Filter\n\nThe full inspection dataset includes certification types that are not directly related to fire safety or are attributed to industrial building regulation which are fewer in number and can introduce noise as they also function differently, specifically Facade Reports, Pier Reports, Private Bridge Reports, Damper Certifications, Special Hazards Certifications, and Emergency and Standby Power Systems Certifications. These inspection categories have fundamentally different failure criteria and enforcement contexts compared to fire safety certifications such as Sprinkler, Smoke Control, and Fire Alarm certifications. Including them would conflate structurally distinct inspection types and introduce systematic noise into the outcome variable. Retaining only fire-safety-relevant certification types ensures that the model is predicting failure within a coherent and comparable set of inspections.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nli_sf <- li_sf %>%\n  filter(!buildingcerttype %in% c(\n    \"Special Hazards Certification\",\n    \"Emergency and Standby Power Systems Certification\",\n    \"Damper Certification\",\n    \"Facade Report\",\n    \"Pier Report\",\n    \"Private Bridge Report\"\n  ))\n\ncat(\"Certification types retained after filter:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCertification types retained after filter:\n```\n\n\n:::\n\n```{.r .cell-code}\nli_sf%>%\n  count(buildingcerttype, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 5 features and 2 fields\nGeometry type: MULTIPOINT\nDimension:     XY\nBounding box:  xmin: 476585.3 ymin: 4414286 xmax: 503599.2 ymax: 4442638\nProjected CRS: NAD83 / UTM zone 18N\n             buildingcerttype     n                       geometry\n1    Fire Alarm Certification 15291 MULTIPOINT ((476585.3 44252...\n2     Sprinkler Certification  6359 MULTIPOINT ((476585.3 44252...\n3          Fire Escape Report   257 MULTIPOINT ((477711.8 44251...\n4 Smoke Control Certification    35 MULTIPOINT ((478830.2 44267...\n5     Standpipe Certification    18 MULTIPOINT ((478613 4415034...\n```\n\n\n:::\n:::\n\n\n## Joining Fire Inspections to OPA Properties\n\nThe L&I inspection dataset does not include property-level characteristics such as building age, market value, or land use category. These are critical features for predicting inspection failure for older buildings, lower-value properties, and certain land use types are theoretically more likely to have deferred maintenance and code violations. The Office of Property Assessment dataset provides these characteristics for all Philadelphia properties on sale. Because there is no shared unique identifier between the two datasets, a nearest-neighbour spatial join is used to match each inspection record to its closest OPA property. Match quality is assessed using the distance between the inspection point and its matched OPA record. Matches greater than 100 metres are flagged and excluded as likely geocoding errors or cases where the inspection point did not correspond to a specific addressable property in the OPA data. This threshold was chosen to balance data retention against match accuracy, 421 or 1.92% of the properties were dropped due to poor match.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopa_prop <- st_read((\"data/opa_properties_public.geojson\"), quiet = TRUE) %>%\n  st_transform(26918)\n\nopa_prop_filtered <- opa_prop %>%\n  select(category_code, category_code_description,\n         interior_condition,\n         market_value, total_livable_area, year_built, geometry) %>%\n  mutate(age = 2025 - as.numeric(year_built)) %>%\n  filter(age >= 0 & age < 2025) %>%\n  filter(!st_is_empty(geometry))\n\nst_crs(li_sf) == st_crs(opa_prop_filtered)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n### Map: Fire Inspections vs OPA Properties\n\nThe map overlays fire inspection points (red) on OPA property locations (blue) across Philadelphia. The close correspondence between the two layers confirms that the nearest-neighbour join is operating correctly, inspection points and their matched OPA properties are geographically proximate across the city. Areas of high inspection density correspond to denser residential and commercial neighbourhoods where fire safety certification requirements are more prevalent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly_26918 <- philly %>%\n  st_transform(26918)\n\nggplot() +\n  geom_sf(data = philly_26918, fill = \"grey95\", color = \"black\", linewidth = 0.8) +\n  geom_sf(data = opa_prop_filtered, color = \"steelblue\", fill = \"steelblue\",\n          alpha = 0.3, size = 0.5) +\n  geom_sf(data = li_sf, color = \"red\", alpha = 0.1, size = 1, shape = 16) +\n  coord_sf(xlim = st_bbox(philly_26918)[c(1, 3)],\n           ylim = st_bbox(philly_26918)[c(2, 4)]) +\n  labs(\n    title    = \"Fire Inspections vs OPA Properties\",\n    subtitle = \"Red = fire inspection points  |  Blue = OPA property records\",\n    caption  = \"Source: OpenDataPhilly, OPA Philadelphia\"\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/map-fire-vs-opa-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnearest_idx <- st_nearest_feature(li_sf, opa_prop_filtered)\n\nfire_insp_opa <- cbind(\n  li_sf,\n  st_drop_geometry(opa_prop_filtered[nearest_idx, ])\n)\n\nfire_insp_opa$match_dist <- st_distance(\n li_sf,\n  opa_prop_filtered[nearest_idx, ],\n  by_element = TRUE\n)\n\nsummary(fire_insp_opa$match_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n  0.6368  13.7707  19.3895  26.1214  28.5839 622.9690 \n```\n\n\n:::\n\n```{.r .cell-code}\nfire_insp_opa$match_dist <- as.numeric(fire_insp_opa$match_dist)\n\nfire_insp_opa <- fire_insp_opa %>%\n  mutate(poor_match = match_dist > 100)\n\nfire_insp_opa_clean <- fire_insp_opa %>%\n  filter(!poor_match)\n\n# Log transform skewed OPA variables\nfire_insp_opa_clean <- fire_insp_opa_clean %>%\n  mutate(\n    log_market_value = log1p(market_value),\n    log_livable_area = log1p(total_livable_area)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Records before match distance filter:\", nrow(fire_insp_opa), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecords before match distance filter: 21960 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Records with match_dist > 100m (poor matches):\", sum(fire_insp_opa$match_dist > 100), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecords with match_dist > 100m (poor matches): 421 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Share dropped:\", round(\n  sum(fire_insp_opa$match_dist > 100) / nrow(fire_insp_opa) * 100, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShare dropped: 1.92 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Final records in fire_insp_opa_clean:\", nrow(fire_insp_opa_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFinal records in fire_insp_opa_clean: 21539 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nOPA joined variable summary (post-filter):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOPA joined variable summary (post-filter):\n```\n\n\n:::\n\n```{.r .cell-code}\nfire_insp_opa_clean %>%\n  st_drop_geometry() %>%\n  select(age, market_value, total_livable_area, interior_condition) %>%\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age         market_value       total_livable_area interior_condition\n Min.   :  0.0   Min.   :     1100   Min.   :      0    Length:21539      \n 1st Qu.: 63.0   1st Qu.:   259950   1st Qu.:   1800    Class :character  \n Median :100.0   Median :   510700   Median :   2800    Mode  :character  \n Mean   : 86.3   Mean   :  3007338   Mean   :  17708                      \n 3rd Qu.:110.0   3rd Qu.:  1075500   3rd Qu.:   5880                      \n Max.   :316.0   Max.   :442765700   Max.   :1588163                      \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections_fire_opa <- fire_insp_opa_clean %>%\n  st_transform(crs = 4326)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Feature Engineering\n\n## Property-Level Spatial Features\n\nThree property-level spatial features are computed: distance to the nearest failed inspection (capturing spatial clustering of risk), distance to Philadelphia City Hall (capturing urban core vs periphery variation), and distance to the nearest SEPTA transit stop (a proxy for accessibility). All distances are computed in UTM 26918 (metres). Two buffer-based features additionally capture local context within 500 metres of each property: the count of 311 maintenance complaints and the count of code violations (log-transformed).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nli_sf <- inspections_fire_opa %>% \n  st_transform(26918)\n\n\nviolations_sf <- read_csv(\"data/violations.csv\") %>%\n  drop_na(lng, lat) %>%\n  st_as_sf(coords = c(\"lng\", \"lat\"), crs = 4326) %>%\n  st_transform(26918)\n\ncases_311_sp <- st_read((\"data/public_cases_fc.shp\"), quiet = TRUE) %>%\n  st_transform(26918)\n\ntransit_sf <- st_read((\"data/transit_stops.geojson\"), quiet = TRUE) %>%\n  st_transform(26918)\n```\n:::\n\n\n**Distance to nearest failed inspection** captures spatial clustering of risk. Buildings geographically close to previously failed inspections are more likely to share similar physical characteristics, building stock age, and maintenance conditions. This feature gives the model a signal about the local risk environment surrounding each property rather than relying solely on neighbourhood demographics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfail_sf <- li_sf %>% filter(fail == 1)\n\nnearest_idx <- st_nearest_feature(li_sf, fail_sf)\n\nli_sf$dist_nearest_fail <- st_distance(\n  li_sf, fail_sf[nearest_idx, ], by_element = TRUE\n) %>% as.numeric()\n\nli_sf$dist_nearest_fail[is.na(li_sf$dist_nearest_fail)] <-\n  max(li_sf$dist_nearest_fail, na.rm = TRUE)\n\nsummary(li_sf$dist_nearest_fail)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00   83.16  191.95  279.79  365.90 2540.98 \n```\n\n\n:::\n:::\n\n\n**Distance to city center** (City Hall) serves as a proxy for building density, building age, land use intensity, and the concentration of older commercial and multifamily stock. Properties closer to the urban core tend to occupy older buildings with more complex fire safety systems, while properties further out tend to be newer and lower density.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncenter_city <- st_sfc(st_point(c(-75.1636, 39.9526)), crs = 4326) %>%\n  st_transform(26918)\n\nli_sf$dist_center <- st_distance(li_sf, center_city) %>% as.numeric()\n\nsummary(li_sf$dist_center)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   80.6  2014.9  3799.9  5659.2  8096.3 24057.8 \n```\n\n\n:::\n:::\n\n\n**Distance to nearest transit stop** is a proxy for neighbourhood accessibility, activity levels, and land use intensity. Areas well-served by transit tend to have higher pedestrian activity, more commercial uses, and denser building stock, all of which correlate with the types of buildings subject to fire safety certification requirements.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnearest_transit <- st_nearest_feature(li_sf, transit_sf)\n\nli_sf$dist_transit <- st_distance(\n  li_sf, transit_sf[nearest_transit, ], by_element = TRUE\n) %>% as.numeric()\n\nsummary(li_sf$dist_transit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n3.417e-02 2.645e+01 5.515e+01 7.936e+01 9.744e+01 1.374e+03 \n```\n\n\n:::\n:::\n\n\n**311 Maintenance Complaints within 500m** captures local complaint activity in the immediate vicinity of each property. Higher complaint density suggests either genuinely worse building conditions or a more engaged population that reports problems—both relevant signals for higher rates of inspection. A 500 metre buffer is used rather than block group aggregation because complaint activity is highly localised.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncases_311_filtered <- cases_311_sp %>%\n  filter(subject == \"Maintenance Complaint\") %>%\n  st_cast(\"POINT\") %>%\n  filter(!st_is_empty(geometry))\n\nbuffer_500 <- st_buffer(li_sf, dist = 500)\n\nli_sf$nearby_311 <- lengths(st_intersects(buffer_500, cases_311_filtered))\n\nsummary(li_sf$nearby_311)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0    66.0   126.0   148.1   205.0   664.0 \n```\n\n\n:::\n:::\n\n\n**Code violations within 500m** is a direct indicator of building maintenance and compliance conditions in the immediate area. Properties surrounded by code violations are more likely to be in neighbourhoods where building upkeep is poor. Like the 311 feature, a 500 metre buffer captures the hyperlocal environment more precisely than a block group boundary. The variable is log-transformed because violation counts are heavily right-skewed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nli_sf$nearby_violations     <- lengths(st_intersects(buffer_500, violations_sf))\nli_sf$nearby_violations_log <- log1p(li_sf$nearby_violations)\n\nsummary(li_sf$nearby_violations_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   7.229   7.776   7.595   8.244   9.325 \n```\n\n\n:::\n:::\n\n\nThe faceted histograms show the distribution of each spatial feature across all inspection records. Distance to nearest failed inspection is right-skewed, most properties are relatively close to a previous failure, consistent with the spatial clustering of inspection failures in particular neighbourhoods. Distance to city center is broadly distributed, reflecting the city-wide coverage of the inspection dataset. Distance to transit is concentrated at lower values, consistent with Philadelphia's relatively dense transit network. Nearby 311 complaints and log-transformed violations are both right-skewed even after transformation, reflecting the hyperlocal concentration of complaint and violation activity in specific streets and blocks rather than uniform distribution across neighbourhoods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nli_sf %>%\n  st_drop_geometry() %>%\n  select(dist_nearest_fail, dist_center, dist_transit, nearby_311, nearby_violations_log) %>%\n  pivot_longer(everything(), names_to = \"feature\", values_to = \"value\") %>%\n  ggplot(aes(x = value)) +\n  geom_histogram(fill = \"steelblue\", color = \"white\", bins = 40) +\n  facet_wrap(~feature, scales = \"free\") +\n  labs(\n    title   = \"Distribution of Property-Level Spatial Features\",\n    x       = NULL,\n    y       = \"Count\",\n    caption = \"Source: OpenDataPhilly, SEPTA, L&I\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/spatial-features-summary-1.png){width=864}\n:::\n\n```{.r .cell-code}\ncat(\"Missing values per spatial feature:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing values per spatial feature:\n```\n\n\n:::\n\n```{.r .cell-code}\nli_sf %>%\n  st_drop_geometry() %>%\n  select(dist_nearest_fail, dist_center, dist_transit, nearby_311, nearby_violations_log) %>%\n  summarise(across(everything(), ~sum(is.na(.)))) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  dist_nearest_fail dist_center dist_transit nearby_311 nearby_violations_log\n1                 0           0            0          0                     0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninspections_fire_opa <- li_sf %>% \n  st_transform(crs = 4326)\n```\n:::\n\n\n## OPA Property Features by Block Group\n\nProperties with sale prices at or below \\$10,000 are excluded before computing block group summaries. These records almost certainly represent tax transfers, intra-family sales, foreclosure sales, or recording errors rather than genuine arm's-length market transactions. Including them would severely distort block group average market value calculations in ways that do not reflect actual neighbourhood property conditions.\n\nSingle family, multifamily, and commercial properties are summarised separately rather than aggregated together. These property types have fundamentally different market dynamics, building characteristics, and maintenance patterns. Averaging market value or age across all property types together would obscure these differences, a block group with high average commercial values but low residential values would appear identical to one with uniformly moderate values across both types, yet these represent very different neighbourhood contexts for predicting inspection risk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopa <- st_read((\"data/opa_properties_public.geojson\"),\n  quiet = TRUE\n) %>%\n  filter(sale_price > 10000) %>%\n  mutate(\n    year_built = as.numeric(year_built),\n    age        = 2025 - year_built\n  ) %>%\n  st_transform(crs = 4326)\n\nopa_singlefam  <- opa %>% filter(category_code_description == \"SINGLE FAMILY\")\nopa_multifam   <- opa %>% filter(category_code_description == \"MULTI FAMILY\")\nopa_commercial <- opa %>% filter(category_code_description %in% c(\"COMMERCIAL\", \"MIXED USE\"))\n\n# Align CRS before spatial joins\nblock_groups <- st_transform(block_groups, st_crs(opa))\n\n# Spatial joins — assign each property to its block group\nopa_sf_block_groups <- st_join(\n  opa_singlefam, block_groups %>% select(GEOID, geometry), join = st_within\n)\nopa_mf_block_groups <- st_join(\n  opa_multifam, block_groups %>% select(GEOID, geometry), join = st_within\n)\nopa_commercial_block_groups <- st_join(\n  opa_commercial, block_groups %>% select(GEOID, geometry), join = st_within\n)\n\n# Block group summaries — single family\nopa_sf_block_group_summary <- opa_sf_block_groups %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarize(\n    sf_n_properties        = n(),\n    sf_avg_market_value    = mean(market_value, na.rm = TRUE),\n    sf_avg_sale_price      = mean(sale_price, na.rm = TRUE),\n    sf_avg_number_bedrooms = mean(number_of_bedrooms, na.rm = TRUE),\n    sf_avg_total_area      = mean(total_area, na.rm = TRUE),\n    sf_avg_livable_area    = mean(total_livable_area, na.rm = TRUE),\n    sf_avg_age             = mean(age, na.rm = TRUE)\n  )\n\n# Block group summaries — multifamily\nopa_mf_block_group_summary <- opa_mf_block_groups %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarize(\n    mf_n_properties        = n(),\n    mf_avg_market_value    = mean(market_value, na.rm = TRUE),\n    mf_avg_sale_price      = mean(sale_price, na.rm = TRUE),\n    mf_avg_number_bedrooms = mean(number_of_bedrooms, na.rm = TRUE),\n    mf_avg_total_area      = mean(total_area, na.rm = TRUE),\n    mf_avg_livable_area    = mean(total_livable_area, na.rm = TRUE),\n    mf_avg_age             = mean(age, na.rm = TRUE)\n  )\n\n# Block group summaries — commercial and mixed use\nopa_commercial_block_group_summary <- opa_commercial_block_groups %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarize(\n    comm_n_properties     = n(),\n    comm_avg_market_value = mean(market_value, na.rm = TRUE),\n    comm_avg_sale_price   = mean(sale_price, na.rm = TRUE),\n    comm_avg_total_area   = mean(total_area, na.rm = TRUE),\n    comm_avg_age          = mean(age, na.rm = TRUE)\n  )\n```\n:::\n\n\n## OPA Neighbourhood Context: Exploratory Maps\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblock_groups_sf <- block_groups %>%\n  left_join(opa_sf_block_group_summary, by = \"GEOID\")\n\nblock_groups_mf <- block_groups %>%\n  left_join(opa_mf_block_group_summary, by = \"GEOID\")\n\nblock_groups_commercial <- block_groups %>%\n  left_join(opa_commercial_block_group_summary, by = \"GEOID\")\n```\n:::\n\n\n### Average Sale Price by Block Group\n\nThe three choropleth maps show the spatial distribution of average sale price for single family, multifamily, and commercial properties across Philadelphia block groups, capped at the 95th percentile to prevent extreme outliers from dominating the colour scale. Clear spatial gradients are visible in all three maps, Centre City and surrounding neighbourhoods show higher average values, while North and West Philadelphia show lower values. These gradients reflect real differences in neighbourhood investment and building stock quality that are theoretically linked to inspection outcomes. The spatial variation confirms that these block group summaries carry meaningful geographic signal for the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_sf <- quantile(block_groups_sf$sf_avg_sale_price, 0.95, na.rm = TRUE)\n\nblock_groups_sf <- block_groups_sf %>%\n  mutate(avg_sale_price_capped = pmin(sf_avg_sale_price, cap_sf))\n\nggplot() +\n  geom_sf(data = block_groups_sf, aes(fill = avg_sale_price_capped), color = NA) +\n  scale_fill_viridis_c(\n    option   = \"plasma\",\n    na.value = \"grey80\",\n    labels   = scales::dollar_format(scale = 0.001, suffix = \"K\"),\n    name     = \"Avg Sale Price\\n(capped at 95th %ile)\"\n  ) +\n  labs(\n    title    = \"Average Sale Price by Block Group\",\n    subtitle = \"Single Family Properties, Philadelphia PA\",\n    caption  = \"Source: OPA Philadelphia\"\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/opa-maps-1.png){width=864}\n:::\n\n```{.r .cell-code}\ncap_mf <- quantile(block_groups_mf$mf_avg_sale_price, 0.95, na.rm = TRUE)\n\nblock_groups_mf <- block_groups_mf %>%\n  mutate(avg_sale_price_capped = pmin(mf_avg_sale_price, cap_mf))\n\nggplot() +\n  geom_sf(data = block_groups_mf, aes(fill = avg_sale_price_capped), color = NA) +\n  scale_fill_viridis_c(\n    option   = \"plasma\",\n    na.value = \"grey80\",\n    labels   = scales::dollar_format(scale = 0.001, suffix = \"K\"),\n    name     = \"Avg Sale Price\\n(capped at 95th %ile)\"\n  ) +\n  labs(\n    title    = \"Average Sale Price by Block Group\",\n    subtitle = \"Multifamily Properties, Philadelphia PA\",\n    caption  = \"Source: OPA Philadelphia\"\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/opa-maps-2.png){width=864}\n:::\n\n```{.r .cell-code}\ncap_comm <- quantile(block_groups_commercial$comm_avg_sale_price, 0.95, na.rm = TRUE)\n\nblock_groups_commercial <- block_groups_commercial %>%\n  mutate(avg_sale_price_capped = pmin(comm_avg_sale_price, cap_comm))\n\nggplot() +\n  geom_sf(data = block_groups_commercial, aes(fill = avg_sale_price_capped), color = NA) +\n  scale_fill_viridis_c(\n    option   = \"plasma\",\n    na.value = \"grey80\",\n    labels   = scales::dollar_format(scale = 0.001, suffix = \"K\"),\n    name     = \"Avg Sale Price\\n(capped at 95th %ile)\"\n  ) +\n  labs(\n    title    = \"Average Sale Price by Block Group\",\n    subtitle = \"Commercial Properties, Philadelphia PA\",\n    caption  = \"Source: OPA Philadelphia\"\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/opa-maps-3.png){width=864}\n:::\n:::\n\n\n## 311 Fire Requests by Block Group\n\nThe 311 dataset contains requests across many city agencies. Filtering to Fire Department requests isolates complaints that are directly relevant to fire safety conditions, things like illegal burning, smoke complaints, and fire hazard reports. Including all 311 request types would add noise from unrelated complaints such as pothole repairs or noise complaints, diluting the signal from fire-specific complaint activity that is theoretically linked to inspection outcomes. These types of 311 requests could help improve things that could influence fire inspection, or correspond it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphl_311 <- phl_311 %>%\n  filter(agency_responsible == \"Fire Department\") %>%\n  st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326) %>%\n  st_transform(st_crs(block_groups))\n\nphl311_block_groups <- st_join(\n  phl_311, block_groups %>% select(GEOID, geometry), join = st_within\n)\n\nbg_summary_311 <- phl311_block_groups %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarize(n_requests = n()) %>%\n  mutate(n_requests = replace_na(n_requests, 0))\n```\n:::\n\n\n## Inspection Distance Features by Block Group\n\nBlock groups are used as the spatial unit for neighbourhood-level aggregation. They sit between census tracts and census blocks in geographic granularity. Tracts are too large, they can contain thousands of properties spanning very different neighbourhood conditions, smoothing out variation that matters for predicting inspection failure. Census blocks are too small, many contain only a handful of properties, making summary statistics like average market value or average age unstable and unreliable. Block groups typically contain 600–3,000 people and produce stable averages while still capturing meaningful local variation in neighbourhood conditions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbg_fire_opa_insp <- st_join(\n  inspections_fire_opa %>% st_transform(st_crs(block_groups)),\n  block_groups %>% select(GEOID, geometry),\n  join = st_within\n)\n\nbg_fire_opa_insp_summ <- bg_fire_opa_insp %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarize(\n    avg_dst_nr_  = mean(dist_nearest_fail,  na.rm = TRUE),\n    avg_dst_cntr = mean(dist_center,  na.rm = TRUE),\n    avg_dst_trn  = mean(dist_transit,  na.rm = TRUE)\n  )\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Model Dataset Construction\n\nThe final modeling dataset combines property-level inspection outcomes with neighbourhood demographic conditions, spatial accessibility measures, complaint activity, and surrounding property characteristics. Each observation represents an individual property from `inspections_fire_opa`. Spatial joins attach block-group level contextual information to each property, allowing the model to evaluate buildings within their broader neighbourhood environment rather than in isolation.\n\nThe dataset integrates the following sources:\n\n-   Philadelphia fire inspection outcomes (L&I)\n-   Office of Property Assessment (OPA) property data\n-   Census block group demographic indicators (ACS 2022)\n-   311 service request activity (Fire Department)\n-   Spatial accessibility and proximity measures\n-   Aggregated neighbourhood property characteristics\n\nHeavily skewed count and value variables are log-transformed using `log1p()`, which safely handles zeros while compressing the right tail and stabilising variance for logistic regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data <- inspections_fire_opa %>%\n  st_transform(crs = st_crs(block_groups)) %>%\n  st_join(block_groups %>% select(GEOID, geometry), join = st_within) %>%\n  st_drop_geometry() %>%\n  left_join(opa_sf_block_group_summary, by = \"GEOID\") %>%\n  left_join(opa_mf_block_group_summary, by = \"GEOID\") %>%\n  left_join(opa_commercial_block_group_summary, by = \"GEOID\") %>%\n  left_join(bg_summary_311, by = \"GEOID\") %>%\n  left_join(bg_fire_opa_insp_summ, by = \"GEOID\") %>%\n  left_join(phl_census %>% st_drop_geometry(), by = \"GEOID\") %>%\n  mutate(\n    # Outcome\n    high_risk         = as.integer(fail == 1),\n    # Replace count NAs with 0\n    n_requests        = replace_na(n_requests, 0),\n    sf_n_properties   = replace_na(sf_n_properties, 0),\n    mf_n_properties   = replace_na(mf_n_properties, 0),\n    comm_n_properties = replace_na(comm_n_properties, 0),\n    # Log transforms (log1p handles zeros safely)\n    log_n_comm_properties   = log1p(comm_n_properties),\n    log_comm_avg_mv         = log1p(comm_avg_market_value),\n    log_comm_avg_age        = log1p(comm_avg_age),\n    log_comm_avg_total_area = log1p(comm_avg_total_area),\n    log_n_sf_properties     = log1p(sf_n_properties),\n    log_sf_avg_mv           = log1p(sf_avg_market_value),\n    log_sf_avg_age          = log1p(sf_avg_age),\n    log_mf_avg_mv           = log1p(mf_avg_market_value),\n    log_mf_avg_age          = log1p(mf_avg_age),\n    log_avg_vac_units       = log1p(Vacant_Units),\n    log_n_requests          = log1p(n_requests)\n  ) %>%\n  filter(!is.na(high_risk))\n\ncat(\"Outcome distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOutcome distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(table(model_data$high_risk))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1 \n20579   960 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"% high risk:\", round(mean(model_data$high_risk) * 100, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n% high risk: 4.46 \n```\n\n\n:::\n:::\n\n\nThe final outcome variable, `high_risk`, is coded as a binary indicator equal to 1 if a property fails inspection and 0 otherwise. The resulting dataset contains 21,539 observations, of which approximately 4.46% are classified as high risk — confirming a substantial class imbalance that must be addressed before modeling.\n\n## Train/Test Split\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ntrainIndex <- createDataPartition(y = model_data$high_risk, p = 0.70, list = FALSE)\ntrain_data <- model_data[trainIndex, ]\ntest_data  <- model_data[-trainIndex, ]\n```\n:::\n\n\nApproximately 70% of observations are allocated to training and 30% to testing. The model is fit exclusively on training data and evaluated on the held-out test set, reflecting a realistic deployment scenario where historical patterns are used to prioritize future inspections.\n\n------------------------------------------------------------------------\n\n# Modeling Approach\n\nOur objective is to predict whether a building fails inspection, making this a binary classification problem. We use logistic regression to model the probability that a building is classified as high risk.\n\nLogistic regression is appropriate here because the outcome is binary, and because it produces interpretable coefficients that can be translated into odds ratios — important in a policy setting where city officials must understand not only which buildings are high risk, but also what factors drive that risk.\n\nThe model incorporates:\n\n-   Spatial features capturing geographic clustering\n-   Neighbourhood demographic characteristics\n-   Property-level indicators\n-   Interaction terms capturing context-dependent risk\n-   Certification type fixed effects\n\n------------------------------------------------------------------------\n\n# Model Iteration\n\nWe develop the model iteratively, beginning with a simple baseline specification and progressively incorporating additional variables, interaction terms, class balancing strategies, and fixed effects. This staged approach allows us to evaluate how each modeling decision affects predictive performance.\n\n## Model 1: Baseline\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model_1 <- glm(\n  high_risk ~\n    avg_dst_nr_ + avg_dst_trn + avg_dst_cntr +\n    log_n_comm_properties + log_comm_avg_mv + log_comm_avg_age +\n    log_n_sf_properties + log_sf_avg_mv + log_sf_avg_age +\n    log_mf_avg_mv + log_mf_avg_age +\n    log_n_requests +\n    Med_Inc + Vacancy_Rate + Pct_Renter_Occupied + Rent_Burden,\n  data   = train_data,\n  family = \"binomial\"\n)\n\ntest_data$predicted_prob  <- predict(logit_model_1, newdata = test_data, type = \"response\")\ntest_data$predicted_class <- as.integer(test_data$predicted_prob > 0.5)\n\ncat(\"Model 1 Confusion Matrix:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 1 Confusion Matrix:\n```\n\n\n:::\n\n```{.r .cell-code}\nconfusionMatrix(factor(test_data$predicted_class), factor(test_data$high_risk), positive = \"1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction    0    1\n         0 4600  192\n         1    1    1\n                                          \n               Accuracy : 0.9597          \n                 95% CI : (0.9538, 0.9651)\n    No Information Rate : 0.9597          \n    P-Value [Acc > NIR] : 0.5191          \n                                          \n                  Kappa : 0.0094          \n                                          \n Mcnemar's Test P-Value : <2e-16          \n                                          \n            Sensitivity : 0.0051813       \n            Specificity : 0.9997827       \n         Pos Pred Value : 0.5000000       \n         Neg Pred Value : 0.9599332       \n             Prevalence : 0.0402587       \n         Detection Rate : 0.0002086       \n   Detection Prevalence : 0.0004172       \n      Balanced Accuracy : 0.5024820       \n                                          \n       'Positive' Class : 1               \n                                          \n```\n\n\n:::\n\n```{.r .cell-code}\nroc_m1 <- roc(test_data$high_risk, test_data$predicted_prob, quiet = TRUE)\ncat(\"Model 1 AUC:\", round(auc(roc_m1), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 1 AUC: 0.782 \n```\n\n\n:::\n:::\n\n\n> **Issue:** Near-zero sensitivity — the model predicts almost no failures due to class imbalance (only \\~4% of inspections fail).\n\nThe baseline model achieves high overall accuracy (\\~96%) and an AUC of 0.758, but the confusion matrix reveals it predicts virtually all buildings as safe. Sensitivity is effectively zero. This illustrates the core problem with imbalanced classification: high accuracy is achieved simply by predicting the majority class. A model that misses all unsafe buildings has no practical value for inspection prioritization.\n\n## Model 2: Add Interactions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model_2 <- glm(\n  fail ~\n    log_comm_avg_mv + log_comm_avg_age + log_n_comm_properties +\n    avg_dst_nr_ + avg_dst_trn + avg_dst_cntr +\n    Vacancy_Rate + Pct_Renter_Occupied + Rent_Burden + Med_Inc +\n    log_n_requests + log_sf_avg_age + log_mf_avg_age +\n    log_comm_avg_age:Med_Inc +\n    avg_dst_nr_:Vacancy_Rate +\n    log_n_requests:Pct_Renter_Occupied +\n    log_comm_avg_mv:log_n_comm_properties,\n  data   = train_data,\n  family = \"binomial\"\n)\n\ntest_data$predicted_prob  <- predict(logit_model_2, newdata = test_data, type = \"response\")\ntest_data$predicted_class <- as.integer(test_data$predicted_prob > 0.5)\n\nconfusionMatrix(factor(test_data$predicted_class), factor(test_data$fail), positive = \"1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction    0    1\n         0 4600  192\n         1    1    1\n                                          \n               Accuracy : 0.9597          \n                 95% CI : (0.9538, 0.9651)\n    No Information Rate : 0.9597          \n    P-Value [Acc > NIR] : 0.5191          \n                                          \n                  Kappa : 0.0094          \n                                          \n Mcnemar's Test P-Value : <2e-16          \n                                          \n            Sensitivity : 0.0051813       \n            Specificity : 0.9997827       \n         Pos Pred Value : 0.5000000       \n         Neg Pred Value : 0.9599332       \n             Prevalence : 0.0402587       \n         Detection Rate : 0.0002086       \n   Detection Prevalence : 0.0004172       \n      Balanced Accuracy : 0.5024820       \n                                          \n       'Positive' Class : 1               \n                                          \n```\n\n\n:::\n\n```{.r .cell-code}\nroc_m2 <- roc(test_data$fail, test_data$predicted_prob, quiet = TRUE)\ncat(\"Model 2 AUC:\", round(auc(roc_m2), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 2 AUC: 0.779 \n```\n\n\n:::\n:::\n\n\n> **Issue:** Still imbalanced — sensitivity remains very low.\n\nModel 2 adds interaction terms to capture context-dependent risk patterns — for example, the relationship between complaint activity and failure may differ across renter-heavy neighbourhoods, and older commercial buildings may pose different levels of risk across income contexts. Despite a more theoretically informed specification, the AUC (0.753) is nearly identical to Model 1 and sensitivity remains near zero. Improving model specification alone is insufficient when failure cases are heavily underrepresented in training data.\n\n## Addressing Class Imbalance\n\nOnly approximately 4–5% of inspections result in failure, creating a severe class imbalance. We apply upsampling to the training data to increase the representation of failure cases during training, preventing the model from collapsing into majority-class predictions. This is particularly important in policy contexts where the cost of missing unsafe buildings substantially exceeds the cost of additional inspections.\n\n## Model 3: Upsampling + Lower Threshold\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data_balanced <- upSample(\n  x     = train_data %>% select(-fail),\n  y     = factor(train_data$fail),\n  yname = \"fail\"\n) %>%\n  mutate(fail = as.integer(as.character(fail)))\n\ncat(\"Balanced class distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalanced class distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(table(train_data_balanced$fail))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1 \n14422 14422 \n```\n\n\n:::\n\n```{.r .cell-code}\nlogit_model_3 <- glm(\n  fail ~\n    avg_dst_nr_ + avg_dst_trn + avg_dst_cntr +\n    Vacancy_Rate + log_comm_avg_mv + Med_Inc + Pct_Renter_Occupied +\n    avg_dst_nr_:Vacancy_Rate +\n    Pct_Renter_Occupied:log_n_requests +\n    log_comm_avg_age:Med_Inc,\n  data   = train_data_balanced,\n  family = \"binomial\"\n)\n\ntest_data$predicted_prob  <- predict(logit_model_3, newdata = test_data, type = \"response\")\ntest_data$predicted_class <- as.integer(test_data$predicted_prob > 0.3)\n\nconfusionMatrix(factor(test_data$predicted_class), factor(test_data$fail), positive = \"1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction    0    1\n         0 2044   12\n         1 2954  214\n                                          \n               Accuracy : 0.4322          \n                 95% CI : (0.4187, 0.4458)\n    No Information Rate : 0.9567          \n    P-Value [Acc > NIR] : 1               \n                                          \n                  Kappa : 0.0493          \n                                          \n Mcnemar's Test P-Value : <2e-16          \n                                          \n            Sensitivity : 0.94690         \n            Specificity : 0.40896         \n         Pos Pred Value : 0.06755         \n         Neg Pred Value : 0.99416         \n             Prevalence : 0.04326         \n         Detection Rate : 0.04096         \n   Detection Prevalence : 0.60643         \n      Balanced Accuracy : 0.67793         \n                                          \n       'Positive' Class : 1               \n                                          \n```\n\n\n:::\n\n```{.r .cell-code}\nroc_m3 <- roc(test_data$fail, test_data$predicted_prob, quiet = TRUE)\ncat(\"Model 3 AUC:\", round(auc(roc_m3), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 3 AUC: 0.778 \n```\n\n\n:::\n:::\n\n\n> **Issue:** Sensitivity now 94% but specificity only 35% — the model flags too many buildings as high risk.\n\nUpsampling substantially changes model behavior. Sensitivity rises to \\~0.94, demonstrating that class imbalance — not model structure — was the primary factor suppressing performance. However, specificity drops to \\~0.35. The model has swung from overly conservative to overly precautionary. Threshold selection and balancing strategies are both critical components of model design in rare-event policy problems.\n\n## Certification Type Fixed Effects\n\nInspection categories differ substantially in their baseline failure rates — sprinkler inspections fail at significantly higher rates than other types. To prevent the model from conflating inspection difficulty with underlying building risk, we include certification type (`bldngcrtt`) as a categorical fixed effect, allowing the model to compare buildings within similar inspection categories rather than treating all inspections as equivalent.\n\n## Model 4: Add Certification Type Fixed Effects + Threshold Scan\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model_4 <- glm(\n  fail ~\n    avg_dst_nr_ + avg_dst_trn + avg_dst_cntr +\n    Vacancy_Rate + Med_Inc + Pct_Renter_Occupied + Rent_Burden +\n    log_comm_avg_mv + log_comm_avg_age + log_n_comm_properties +\n    log_sf_avg_mv + log_sf_avg_age +\n    log_mf_avg_mv + log_mf_avg_age +\n    log_n_requests +\n    buildingcerttype +\n    avg_dst_nr_:Vacancy_Rate +\n    Pct_Renter_Occupied:log_n_requests +\n    log_comm_avg_age:Med_Inc +\n    Vacancy_Rate:Med_Inc +\n    log_comm_avg_mv:avg_dst_cntr +\n    Pct_Renter_Occupied:Vacancy_Rate,\n  data   = train_data_balanced,\n  family = \"binomial\"\n)\n\ntest_data$predicted_prob <- predict(logit_model_4, newdata = test_data, type = \"response\")\nroc_m4 <- roc(test_data$fail, test_data$predicted_prob, quiet = TRUE)\ncat(\"Model 4 AUC:\", round(auc(roc_m4), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 4 AUC: 0.819 \n```\n\n\n:::\n:::\n\n\nModel 4 achieves an AUC of 0.803 — the strongest performance across all specifications — by combining balanced training data, contextual interaction effects, and certification-type fixed effects. The model remains interpretable despite increased complexity.\n\n------------------------------------------------------------------------\n\n# Final Model\n\nInsignificant predictors (`log_sf_avg_age`, `Vacancy_Rate:Med_Inc`, `Vacancy_Rate:Pct_Renter_Occupied`) are dropped for parsimony.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model_final <- glm(\n  fail ~\n    avg_dst_nr_ + avg_dst_trn + avg_dst_cntr +\n    Vacancy_Rate + Med_Inc + Pct_Renter_Occupied + Rent_Burden +\n    log_comm_avg_mv + log_comm_avg_age + log_n_comm_properties +\n    log_sf_avg_mv +\n    log_mf_avg_mv + log_mf_avg_age +\n    log_n_requests +\n    buildingcerttype +\n    avg_dst_nr_:Vacancy_Rate +\n    Pct_Renter_Occupied:log_n_requests +\n    log_comm_avg_age:Med_Inc +\n    avg_dst_cntr:log_comm_avg_mv,\n  data   = train_data_balanced,\n  family = \"binomial\"\n)\n\nsummary(logit_model_final)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = fail ~ avg_dst_nr_ + avg_dst_trn + avg_dst_cntr + \n    Vacancy_Rate + Med_Inc + Pct_Renter_Occupied + Rent_Burden + \n    log_comm_avg_mv + log_comm_avg_age + log_n_comm_properties + \n    log_sf_avg_mv + log_mf_avg_mv + log_mf_avg_age + log_n_requests + \n    buildingcerttype + avg_dst_nr_:Vacancy_Rate + Pct_Renter_Occupied:log_n_requests + \n    log_comm_avg_age:Med_Inc + avg_dst_cntr:log_comm_avg_mv, \n    family = \"binomial\", data = train_data_balanced)\n\nCoefficients:\n                                              Estimate Std. Error z value\n(Intercept)                                  9.995e-01  7.421e-01   1.347\navg_dst_nr_                                 -8.751e-03  3.347e-04 -26.149\navg_dst_trn                                  5.358e-03  4.418e-04  12.128\navg_dst_cntr                                 2.619e-04  6.138e-05   4.267\nVacancy_Rate                                 2.141e-02  4.376e-03   4.893\nMed_Inc                                     -2.142e-05  3.383e-06  -6.332\nPct_Renter_Occupied                         -8.264e-03  1.331e-03  -6.207\nRent_Burden                                  8.243e-03  2.186e-03   3.771\nlog_comm_avg_mv                              2.638e-01  2.948e-02   8.948\nlog_comm_avg_age                            -3.063e-01  5.649e-02  -5.422\nlog_n_comm_properties                       -1.327e-01  1.990e-02  -6.667\nlog_sf_avg_mv                               -4.546e-01  4.612e-02  -9.857\nlog_mf_avg_mv                                1.799e-01  2.325e-02   7.740\nlog_mf_avg_age                               1.726e-01  6.327e-02   2.727\nlog_n_requests                              -1.784e-01  7.844e-02  -2.274\nbuildingcerttypeFire Escape Report          -1.492e+01  1.112e+02  -0.134\nbuildingcerttypeSmoke Control Certification  1.432e-01  4.031e-01   0.355\nbuildingcerttypeSprinkler Certification      1.251e+00  3.451e-02  36.246\nbuildingcerttypeStandpipe Certification     -1.524e+01  4.697e+02  -0.032\navg_dst_nr_:Vacancy_Rate                    -1.872e-04  2.706e-05  -6.919\nPct_Renter_Occupied:log_n_requests           7.796e-03  1.268e-03   6.149\nMed_Inc:log_comm_avg_age                     4.457e-06  6.682e-07   6.671\navg_dst_cntr:log_comm_avg_mv                -1.387e-05  4.432e-06  -3.129\n                                            Pr(>|z|)    \n(Intercept)                                 0.177999    \navg_dst_nr_                                  < 2e-16 ***\navg_dst_trn                                  < 2e-16 ***\navg_dst_cntr                                1.98e-05 ***\nVacancy_Rate                                9.92e-07 ***\nMed_Inc                                     2.42e-10 ***\nPct_Renter_Occupied                         5.40e-10 ***\nRent_Burden                                 0.000162 ***\nlog_comm_avg_mv                              < 2e-16 ***\nlog_comm_avg_age                            5.90e-08 ***\nlog_n_comm_properties                       2.61e-11 ***\nlog_sf_avg_mv                                < 2e-16 ***\nlog_mf_avg_mv                               9.97e-15 ***\nlog_mf_avg_age                              0.006388 ** \nlog_n_requests                              0.022976 *  \nbuildingcerttypeFire Escape Report          0.893252    \nbuildingcerttypeSmoke Control Certification 0.722324    \nbuildingcerttypeSprinkler Certification      < 2e-16 ***\nbuildingcerttypeStandpipe Certification     0.974109    \navg_dst_nr_:Vacancy_Rate                    4.54e-12 ***\nPct_Renter_Occupied:log_n_requests          7.80e-10 ***\nMed_Inc:log_comm_avg_age                    2.54e-11 ***\navg_dst_cntr:log_comm_avg_mv                0.001754 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 29073  on 20994  degrees of freedom\nResidual deviance: 20961  on 20972  degrees of freedom\n  (7849 observations deleted due to missingness)\nAIC: 21007\n\nNumber of Fisher Scoring iterations: 14\n```\n\n\n:::\n:::\n\n\nThe final model drops three statistically insignificant terms from Model 4 while retaining all variables with strong theoretical and empirical relevance. Key patterns from the final specification:\n\n-   Higher vacancy rates are associated with elevated inspection risk\n-   Greater renter concentration is associated with higher predicted risk\n-   Complaint activity becomes more predictive in renter-heavy areas\n-   Commercial property conditions interact with neighbourhood context in important ways\n-   Spatial accessibility measures remain strongly associated with failure outcomes\n\nThe interaction terms demonstrate that risk factors operate differently across neighbourhood contexts rather than having uniform citywide effects.\n\n## Odds Ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(OR = coef(logit_model_final), confint(logit_model_final))) %>%\n  as.data.frame() %>%\n  rownames_to_column(\"Variable\") %>%\n  knitr::kable(digits = 3, caption = \"Odds Ratios — Final Logistic Regression Model\") %>%\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Odds Ratios — Final Logistic Regression Model</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> OR </th>\n   <th style=\"text-align:right;\"> 2.5 % </th>\n   <th style=\"text-align:right;\"> 97.5 % </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 2.717 </td>\n   <td style=\"text-align:right;\"> 0.635 </td>\n   <td style=\"text-align:right;\"> 1.164200e+01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> avg_dst_nr_ </td>\n   <td style=\"text-align:right;\"> 0.991 </td>\n   <td style=\"text-align:right;\"> 0.991 </td>\n   <td style=\"text-align:right;\"> 9.920000e-01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> avg_dst_trn </td>\n   <td style=\"text-align:right;\"> 1.005 </td>\n   <td style=\"text-align:right;\"> 1.004 </td>\n   <td style=\"text-align:right;\"> 1.006000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> avg_dst_cntr </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Vacancy_Rate </td>\n   <td style=\"text-align:right;\"> 1.022 </td>\n   <td style=\"text-align:right;\"> 1.013 </td>\n   <td style=\"text-align:right;\"> 1.030000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Med_Inc </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Pct_Renter_Occupied </td>\n   <td style=\"text-align:right;\"> 0.992 </td>\n   <td style=\"text-align:right;\"> 0.989 </td>\n   <td style=\"text-align:right;\"> 9.940000e-01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Rent_Burden </td>\n   <td style=\"text-align:right;\"> 1.008 </td>\n   <td style=\"text-align:right;\"> 1.004 </td>\n   <td style=\"text-align:right;\"> 1.013000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> log_comm_avg_mv </td>\n   <td style=\"text-align:right;\"> 1.302 </td>\n   <td style=\"text-align:right;\"> 1.229 </td>\n   <td style=\"text-align:right;\"> 1.379000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> log_comm_avg_age </td>\n   <td style=\"text-align:right;\"> 0.736 </td>\n   <td style=\"text-align:right;\"> 0.659 </td>\n   <td style=\"text-align:right;\"> 8.220000e-01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> log_n_comm_properties </td>\n   <td style=\"text-align:right;\"> 0.876 </td>\n   <td style=\"text-align:right;\"> 0.842 </td>\n   <td style=\"text-align:right;\"> 9.110000e-01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> log_sf_avg_mv </td>\n   <td style=\"text-align:right;\"> 0.635 </td>\n   <td style=\"text-align:right;\"> 0.580 </td>\n   <td style=\"text-align:right;\"> 6.950000e-01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> log_mf_avg_mv </td>\n   <td style=\"text-align:right;\"> 1.197 </td>\n   <td style=\"text-align:right;\"> 1.144 </td>\n   <td style=\"text-align:right;\"> 1.253000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> log_mf_avg_age </td>\n   <td style=\"text-align:right;\"> 1.188 </td>\n   <td style=\"text-align:right;\"> 1.050 </td>\n   <td style=\"text-align:right;\"> 1.345000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> log_n_requests </td>\n   <td style=\"text-align:right;\"> 0.837 </td>\n   <td style=\"text-align:right;\"> 0.717 </td>\n   <td style=\"text-align:right;\"> 9.760000e-01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> buildingcerttypeFire Escape Report </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.000000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> buildingcerttypeSmoke Control Certification </td>\n   <td style=\"text-align:right;\"> 1.154 </td>\n   <td style=\"text-align:right;\"> 0.537 </td>\n   <td style=\"text-align:right;\"> 2.647000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> buildingcerttypeSprinkler Certification </td>\n   <td style=\"text-align:right;\"> 3.493 </td>\n   <td style=\"text-align:right;\"> 3.265 </td>\n   <td style=\"text-align:right;\"> 3.738000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> buildingcerttypeStandpipe Certification </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> 4.631695e+10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> avg_dst_nr_:Vacancy_Rate </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Pct_Renter_Occupied:log_n_requests </td>\n   <td style=\"text-align:right;\"> 1.008 </td>\n   <td style=\"text-align:right;\"> 1.005 </td>\n   <td style=\"text-align:right;\"> 1.010000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Med_Inc:log_comm_avg_age </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000000e+00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> avg_dst_cntr:log_comm_avg_mv </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 1.000000e+00 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nValues above 1 indicate increased likelihood of inspection failure; values below 1 indicate decreased risk. The inclusion of certification type fixed effects means these estimates reflect risk patterns *after* accounting for systematic differences across inspection categories — the model is not simply identifying buildings that belong to more failure-prone inspection types.\n\n------------------------------------------------------------------------\n\n# Threshold Selection\n\nWe scan thresholds from 0.01 to 0.99 and select the lowest threshold where sensitivity ≥ 0.80. This prioritizes catching real failures, since missing a building that fails inspection carries life-safety consequences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data$predicted_prob <- predict(\n  logit_model_final, newdata = test_data, type = \"response\"\n)\n\nroc_final <- roc(test_data$fail, test_data$predicted_prob, quiet = TRUE)\ncat(\"Final Model AUC:\", round(auc(roc_final), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFinal Model AUC: 0.819 \n```\n\n\n:::\n\n```{.r .cell-code}\nthresholds <- seq(0.01, 0.99, by = 0.01)\n\nthreshold_results <- map_df(thresholds, function(t) {\n  pred_class <- as.integer(test_data$predicted_prob > t)\n  if (length(unique(pred_class)) < 2) return(NULL)\n  cm <- confusionMatrix(factor(pred_class), factor(test_data$fail), positive = \"1\")\n  tibble(\n    threshold   = t,\n    sensitivity = cm$byClass[\"Sensitivity\"],\n    specificity = cm$byClass[\"Specificity\"],\n    accuracy    = cm$overall[\"Accuracy\"],\n    kappa       = cm$overall[\"Kappa\"],\n    ppv         = cm$byClass[\"Pos Pred Value\"]\n  )\n})\n\nbest_threshold <- threshold_results %>%\n  filter(sensitivity >= 0.80) %>%\n  arrange(desc(specificity)) %>%\n  slice(1)\n\ncat(\"Optimal threshold:\", best_threshold$threshold, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimal threshold: 0.46 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sensitivity:\",       round(best_threshold$sensitivity, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSensitivity: 0.803 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Specificity:\",       round(best_threshold$specificity, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpecificity: 0.688 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Kappa:\",             round(best_threshold$kappa, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKappa: 0.11 \n```\n\n\n:::\n:::\n\n\nThe default threshold of 0.50 is inappropriate here because the costs of false negatives and false positives are highly asymmetric. The optimal threshold identified is 0.42, achieving sensitivity of \\~0.803 and specificity of \\~0.646. Threshold selection is not purely a statistical decision — it reflects how the city prioritizes the relative costs of missing unsafe buildings versus conducting unnecessary inspections.\n\n## Threshold Tradeoff Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthreshold_results %>%\n  pivot_longer(cols = c(sensitivity, specificity, kappa),\n               names_to  = \"metric\",\n               values_to = \"value\") %>%\n  ggplot(aes(x = threshold, y = value, color = metric)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = best_threshold$threshold,\n             linetype = \"dashed\", color = \"grey40\") +\n  annotate(\"text\",\n           x     = best_threshold$threshold + 0.03,\n           y     = 0.5,\n           label = paste(\"t =\", best_threshold$threshold),\n           size  = 3.5) +\n  scale_color_viridis_d(option = \"plasma\") +\n  labs(\n    title    = \"Model Performance Across Thresholds\",\n    subtitle = \"Dashed line = selected threshold (sensitivity ≥ 0.80)\",\n    x        = \"Classification Threshold\",\n    y        = \"Value\",\n    color    = \"Metric\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/threshold-plot-1.png){width=864}\n:::\n:::\n\n\nThe plot illustrates the sensitivity-specificity tradeoff as the threshold varies. Small threshold adjustments substantially alter model behavior and operational outcomes, reinforcing why the default 0.50 is rarely appropriate in rare-event policy settings.\n\n------------------------------------------------------------------------\n\n# Final Model Performance\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data$predicted_class <- as.integer(\n  test_data$predicted_prob > best_threshold$threshold\n)\n\nconfusionMatrix(\n  factor(test_data$predicted_class),\n  factor(test_data$fail),\n  positive = \"1\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction    0    1\n         0 3166   38\n         1 1435  155\n                                          \n               Accuracy : 0.6927          \n                 95% CI : (0.6795, 0.7058)\n    No Information Rate : 0.9597          \n    P-Value [Acc > NIR] : 1               \n                                          \n                  Kappa : 0.11            \n                                          \n Mcnemar's Test P-Value : <2e-16          \n                                          \n            Sensitivity : 0.80311         \n            Specificity : 0.68811         \n         Pos Pred Value : 0.09748         \n         Neg Pred Value : 0.98814         \n             Prevalence : 0.04026         \n         Detection Rate : 0.03233         \n   Detection Prevalence : 0.33166         \n      Balanced Accuracy : 0.74561         \n                                          \n       'Positive' Class : 1               \n                                          \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(roc_final, col = \"#08519c\",\n     main = paste(\"Final Model ROC — AUC =\", round(auc(roc_final), 3)))\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/final-performance-1.png){width=864}\n:::\n:::\n\n\n**Summary of final model performance:**\n\n| Metric | Value | Interpretation |\n|------------------------|------------------------|------------------------|\n| AUC | 0.803 | Good discrimination — model meaningfully separates high and low risk |\n| Sensitivity | 0.808 | Catches 81% of actual failures |\n| Specificity | 0.630 | Correctly clears 63% of safe buildings |\n| NPV | 0.987 | If model says safe, correct 99% of the time |\n| Threshold | 0.420 | Tuned to prioritize recall over precision |\n\nThe extremely high negative predictive value (0.987) is especially important operationally — buildings classified as safe are overwhelmingly likely to pass inspection, making the model useful for screening and prioritizing limited inspection capacity.\n\n------------------------------------------------------------------------\n\n# Model Validation\n\n## 10-Fold Cross-Validation\n\nTests whether performance holds across different data splits. A cross-validated AUC close to the test AUC confirms the model generalizes rather than overfits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv_control <- trainControl(\n  method          = \"cv\",\n  number          = 10,\n  classProbs      = TRUE,\n  summaryFunction = twoClassSummary,\n  savePredictions = TRUE\n)\n\ntrain_data_balanced <- train_data_balanced %>%\n  mutate(fail_factor = factor(ifelse(fail == 1, \"yes\", \"no\")))\n\ntrain_data_balanced_clean <- train_data_balanced %>%\n  select(\n    fail_factor, avg_dst_nr_, avg_dst_trn, avg_dst_cntr,\n    Vacancy_Rate, Med_Inc, Pct_Renter_Occupied, Rent_Burden,\n    log_comm_avg_mv, log_comm_avg_age, log_n_comm_properties,\n    log_sf_avg_mv, log_mf_avg_mv, log_mf_avg_age,\n    log_n_requests, buildingcerttype\n  ) %>%\n  na.omit()\n\ncat(\"Rows used for CV:\", nrow(train_data_balanced_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows used for CV: 20995 \n```\n\n\n:::\n\n```{.r .cell-code}\ncv_model <- train(\n  fail_factor ~\n    avg_dst_nr_ + avg_dst_trn + avg_dst_cntr +\n    Vacancy_Rate + Med_Inc + Pct_Renter_Occupied + Rent_Burden +\n    log_comm_avg_mv + log_comm_avg_age + log_n_comm_properties +\n    log_sf_avg_mv + log_mf_avg_mv + log_mf_avg_age +\n    log_n_requests + buildingcerttype +\n    avg_dst_nr_:Vacancy_Rate +\n    Pct_Renter_Occupied:log_n_requests +\n    log_comm_avg_age:Med_Inc +\n    avg_dst_cntr:log_comm_avg_mv,\n  data      = train_data_balanced_clean,\n  method    = \"glm\",\n  family    = \"binomial\",\n  trControl = cv_control,\n  metric    = \"ROC\"\n)\n\ncat(\"Cross-validated AUC:\", round(cv_model$results$ROC, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCross-validated AUC: 0.831 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cross-validated Sensitivity:\", round(cv_model$results$Sens, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCross-validated Sensitivity: 0.738 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cross-validated Specificity:\", round(cv_model$results$Spec, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCross-validated Specificity: 0.764 \n```\n\n\n:::\n:::\n\n\nCross-validated results (AUC = 0.812, sensitivity = 0.742, specificity = 0.736) are broadly consistent with the held-out test set results, suggesting the model is learning stable and generalizable patterns rather than overfitting to the training data.\n\n## Spatial Autocorrelation of Residuals (Moran's I)\n\nTests whether model errors cluster spatially. Significant clustering indicates geographic patterns the model is missing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract coordinates from original sf object\ninsp_coords <- inspections_fire_opa %>%\n  st_transform(crs = 4326) %>%\n  mutate(\n    lon = st_coordinates(.)[, 1],\n    lat = st_coordinates(.)[, 2]\n  ) %>%\n  st_drop_geometry()\n\n# Join coordinates to test data\ntest_data_sf <- test_data %>%\n  left_join(insp_coords %>% select(objectid, lon, lat), by = \"objectid\") %>%\n  mutate(residual = fail - predicted_prob) %>%\n  filter(!is.na(residual), !is.na(lon), !is.na(lat)) %>%\n  st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326)\n\n# Build spatial weights (jitter to break ties from stacked points)\ncoords <- st_coordinates(test_data_sf)\nset.seed(42)\ncoords_jittered <- coords + matrix(rnorm(nrow(coords) * 2, 0, 0.0001), ncol = 2)\n\nnb    <- knn2nb(knearneigh(coords_jittered, k = 8))\nlistw <- nb2listw(nb, style = \"W\")\n\nmoran_test <- moran.test(test_data_sf$residual, listw)\nprint(moran_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  test_data_sf$residual  \nweights: listw    \n\nMoran I statistic standard deviate = 54.348, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n     3.681871e-01     -2.086376e-04      4.594759e-05 \n```\n\n\n:::\n:::\n\n\nMoran's I ≈ 0.307 (p \\< 2.2e-16) indicates model errors are still geographically clustered. This suggests that some spatial processes affecting inspection failure remain unmodeled after including demographic, complaint, and accessibility variables. While this does not invalidate the model, it points to potential improvements through spatial lag models, geographically weighted regression, or more granular built-environment indicators.\n\n## Residual Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = block_groups, fill = \"grey90\", color = \"white\", linewidth = 0.1) +\n  geom_sf(data = test_data_sf, aes(color = residual), size = 0.5, alpha = 0.6) +\n  scale_color_gradient2(\n    low      = \"#2166ac\",\n    mid      = \"white\",\n    high     = \"#d6604d\",\n    midpoint = 0,\n    name     = \"Residual\\n(actual − predicted)\"\n  ) +\n  labs(\n    title    = \"Spatial Distribution of Model Residuals\",\n    subtitle = \"Red = under-predicted risk  |  Blue = over-predicted risk\",\n    caption  = \"Source: OPA Philadelphia\"\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/residual-map-1.png){width=864}\n:::\n:::\n\n\nSeveral localized residual clusters remain visible, particularly in portions of Center City and surrounding dense neighbourhoods. The residuals are not overwhelmingly concentrated in a single area, suggesting the model captures a substantial portion of the broader geographic risk pattern while leaving some spatial structure unexplained.\n\n## Variable Importance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimportance <- varImp(cv_model, scale = TRUE)\nplot(importance, main = \"Variable Importance — Final Logit Model\")\n```\n\n::: {.cell-output-display}\n![](TechnicalAppendix_Final_v1_files/figure-html/var-importance-1.png){width=864}\n:::\n:::\n\n\nSpatial accessibility variables — particularly distance-based measures — are among the most influential predictors, reinforcing the finding that inspection risk is spatially patterned. Certification type fixed effects (especially sprinkler certification) also emerge as highly important. Several interaction terms rank among the more influential predictors, supporting the decision to incorporate context-dependent relationships into the final specification.\n\n------------------------------------------------------------------------\n\n# Limitations and Bias\n\n**1. Training data reflects enforcement patterns, not true underlying risk.** The model learns from historical inspection outcomes shaped by existing enforcement practices. Because inspections are often complaint-driven, neighbourhoods with higher reporting rates may be overrepresented. The model may partially learn where the city already inspects rather than where risk actually exists.\n\n**2. Underreporting may reinforce inequities.** Communities with lower trust in government or lower reporting rates may generate fewer 311 complaints even when building conditions are poor. This creates a feedback loop: lower reporting → lower predicted risk → fewer inspections → continued under-enforcement. Interaction terms involving renter concentration and complaint activity partially capture these dynamics but cannot fully correct for structural reporting inequities.\n\n**3. Inspection type remains highly influential.** Certification type fixed effects improve model performance but introduce an interpretive limitation. Some inspection categories exhibit much higher baseline failure rates than others, meaning the model is partially predicting inspection type in addition to underlying building condition.\n\n**4. Residual spatial clustering remains present.** Moran's I results indicate that residual errors remain geographically clustered even after incorporating spatial accessibility measures. Future improvements could include spatial lag models, geographically weighted approaches, or more granular built-environment indicators.\n\n**5. False negatives carry meaningful consequences.** Buildings incorrectly classified as low risk may receive lower inspection priority despite potentially unsafe conditions, contributing to delayed enforcement and safety hazards. The model should be interpreted as a decision-support tool rather than a replacement for professional judgment.\n\n**6. Model performance may vary across neighbourhoods.** Residual mapping suggests prediction error is not perfectly uniform across the city, reinforcing the importance of ongoing monitoring, recalibration, and equity evaluation.\n\n**7. Predictive performance does not eliminate policy responsibility.** Decisions regarding enforcement, inspection allocation, and resource prioritization remain policy decisions requiring human oversight, transparency, and accountability.\n\n**8. Liability and governance challenges.** If the model incorrectly classifies a dangerous building as low risk, questions may arise regarding institutional responsibility. Predictive outputs should support — not replace — professional inspection judgment and administrative oversight.\n\n------------------------------------------------------------------------\n\n# Implementation Notes\n\nThis model is best understood as a decision-support and prioritization tool. Its primary value lies in helping the city allocate limited inspection capacity more efficiently by identifying buildings with elevated predicted risk.\n\n**Recommended workflow:**\n\n1.  Run final model on all L&I-registered properties periodically\n2.  Assign predicted failure probability (0–1) to each building\n3.  Sort into risk tiers (High / Medium / Low) by district\n4.  Produce prioritized inspection lists for field staff\n5.  Retrain quarterly as new inspection outcomes accumulate\n\n**Required safeguards:**\n\n**1. Human oversight.** Predicted risk scores should inform inspector decision-making rather than replace it. Inspectors and administrators should retain discretion when allocating inspection resources.\n\n**2. Equity monitoring.** Model performance should be regularly audited across neighbourhoods and census tracts to identify systematic over- or under-prediction in lower-income or historically under-enforced communities.\n\n**3. Transparency and accountability.** The city should maintain clear public documentation describing how the model operates, what variables are used, and how inspection prioritization decisions are made.\n\n**4. Ongoing model monitoring.** Predictive performance should be periodically re-evaluated as inspection practices, reporting patterns, and neighbourhood conditions evolve. Declining performance metrics or changing residual patterns may indicate the need for recalibration or retraining.\n\nImplementation decisions ultimately remain policy decisions rather than purely technical ones. The model can help identify patterns of risk, but decisions regarding enforcement priorities, resource allocation, and acceptable tradeoffs still require human and institutional judgment.\n\n# **References**\n\n-   Pew Charitable Trusts (2021). [Philadelphia's Rental Housing Challenge.](https://www.pew.org/en/research-and-analysis/reports/2021/11/rental-code-enforcement-in-philadelphia)\n\n-   Urban Institute (2022).[Who Is Left Behind by Complaint-Based Code Enforcement?](https://www.urban.org/sites/default/files/2022-09/Improving%20Philadelphia's%20Rental%20Regulatory%20and%20Housing%20Support%20Systems.pdf)\n\n-   National Low Income Housing Coalition (2022). [*Out of Reach: The High Cost of Housing.*](https://nlihc.org/oor)\n\n**Data Sources**\n\n-   Philadelphia Department of Licenses & Inspections: Building Certifications (OpenDataPhilly)\n\n-   City of Philadelphia Office of Property Assessment: `opa_properties_public.geojson`\n\n-   Philadelphia 311 Service Requests: Fire Department calls (OpenDataPhilly)\n\n-   U.S. Census Bureau: American Community Survey 5-Year Estimates, 2022, block group level\n\n-   SEPTA Transit Stops (OpenDataPhilly)\n\n-   L&I Code Violations (OpenDataPhilly)\n",
    "supporting": [
      "TechnicalAppendix_Final_v1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}