---
title: "Arzoo Gupta - MUSA 5080 Portfolio"
---

# Welcome to My Portfolio

This portfolio documents my learning journey in Public Policy Analytics (MUSA 5080). This represents the expertise I've built in analysis, and predictive modeling, it uses spatial, basic ML, binomial, poisson, and time-based models on a wide range of policy issues such as housing prices, infrastructural failure, and micromobility. Presenting the drawbacks and advantages of using automated models and also the issues baked into them as a result of limitations such as data availability. 

## About This Course

Advanced spatial analysis and data science for urban planning and public policy.

## Portfolio Structure

-   **Labs:** Completed assignments and analyses
-   **Final Project:** Capstone modeling challenge

## About Me

I am Arzoo Gupta, a Master of City Planning Student, with a concentration in sustainable transportation and with a background in Sociology and Anthropology, and Political Science. 

## Contact

-   Email: \[gupta4\@upenn.edu\]
-   GitHub: [@arzooguptain-art]
