{
  "hash": "2b0daccdbc2d3a362941152a5173aa13",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 5: Bikeshare SpaceTime Prediction\"\nauthor: \"Arzoo Gupta\"\ndate: today\nformat:\n html:\n    code-fold: true\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\neditor: visual\nexecute:\n  warning: false\n  message: false\n---\n\n# Part 1: Quarter 3\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotTheme <- theme_minimal() + \n  theme( plot.title = element_text(size = 14, face = \"bold\"), \n         plot.subtitle = element_text(size = 10), \n         plot.caption = element_text(size = 8), \n         axis.text.x = element_text(size = 10, angle = 45, hjust = 1), \n         axis.text.y = element_text(size = 10), \n         axis.title = element_text(size = 11, face = \"bold\"), \n         panel.grid.major = element_line(colour = \"#D0D0D0\", linewidth = 0.2),\n         panel.grid.minor = element_blank(), axis.ticks = element_blank(),\n         legend.position = \"right\" )\n\nmapTheme <- theme_void() + \n  theme( plot.title = element_text(size = 14, face = \"bold\"), \n         plot.subtitle = element_text(size = 10), \n         plot.caption = element_text(size = 8), \n         legend.position = \"right\", \n         plot.margin = margin(1, 1, 1, 1, \"cm\"), \n         legend.key.height = unit(1, \"cm\"), \n         legend.key.width = unit(0.2, \"cm\") )\n\npalette5 <- c(\"#eff3ff\", \"#bdd7e7\", \"#6baed6\", \"#3182bd\", \"#08519c\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal trips in Q3 2025: 465464 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDate range: 1751328360 to 1759276680 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnique start stations: 284 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   One Way Round Trip \n    434518      30946 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Day Pass  Indego30 Indego365      NULL   Walk-up \n    18418    252897    157695         5     36449 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nelectric standard \n  299515   165949 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  start_datetime      interval60           week dotw   hour weekend\n  <dttm>              <dttm>              <dbl> <ord> <int>   <dbl>\n1 2025-07-01 00:06:00 2025-07-01 00:00:00    26 Tue       0       0\n2 2025-07-01 00:11:00 2025-07-01 00:00:00    26 Tue       0       0\n3 2025-07-01 00:13:00 2025-07-01 00:00:00    26 Tue       0       0\n4 2025-07-01 00:16:00 2025-07-01 00:00:00    26 Tue       0       0\n5 2025-07-01 00:16:00 2025-07-01 00:00:00    26 Tue       0       0\n6 2025-07-01 00:18:00 2025-07-01 00:00:00    26 Tue       0       0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Trips Over Time\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab_5_files/figure-html/trips_over_time-1.png){width=672}\n:::\n:::\n\n\nDaily ridership in Q3 2025 shows a clear **upward trend** from July through September, with the smoothed trend rising from roughly 4,200 trips/day in early July to over 5,000 by late September. This likely reflects Philadelphians increasingly adopting Indego over the summer as weather stabilizes and days remain long. Strong week-to-week oscillations are visible throughout, the regular valleys correspond to weekends, when commuter demand drops off.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  date       trips\n  <date>     <int>\n1 2025-09-04  6001\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  avg_thursday_trips\n               <dbl>\n1              5306.\n```\n\n\n:::\n:::\n\n\nA notable spike appears around September 4th (the Eagles game), which produced an unusually high 6,001 trips compared to the average Thursday of \\~5,306. This confirms that special events are important candidates for feature engineering.\n\n## Hourly Patterns\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab_5_files/figure-html/hourly_patterns-1.png){width=672}\n:::\n:::\n\n\nWeekdays display a classic bimodal commuter pattern: a morning rush peaking around 8 AM and an even stronger evening rush peaking at 5 PM (hour 17).\n\nThis aligns with the model coefficients that show up later, where hour 17 has the highest coefficient (+1.41), followed closely by hour 18 (+1.12) and hour 8 (+0.84). Weekends, by contrast, show a flatter, single-humped curve peaking in the mid-afternoon (roughly 1–4 PM), reflecting leisure and recreational riding rather than commuting. Weekends also have lower overall trip counts per hour. The clear separation between weekday and weekend patterns confirms that day-type is a critical predictor for the model.\n\n## Top Stations\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Top 20 Indego Stations by Trip Origins</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> start_station </th>\n   <th style=\"text-align:right;\"> start_lat </th>\n   <th style=\"text-align:right;\"> start_lon </th>\n   <th style=\"text-align:right;\"> trips </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 3,010 </td>\n   <td style=\"text-align:right;\"> 39.94711 </td>\n   <td style=\"text-align:right;\"> -75.16618 </td>\n   <td style=\"text-align:right;\"> 7,716 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,032 </td>\n   <td style=\"text-align:right;\"> 39.94527 </td>\n   <td style=\"text-align:right;\"> -75.17971 </td>\n   <td style=\"text-align:right;\"> 5,884 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,213 </td>\n   <td style=\"text-align:right;\"> 39.93887 </td>\n   <td style=\"text-align:right;\"> -75.16663 </td>\n   <td style=\"text-align:right;\"> 5,660 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,163 </td>\n   <td style=\"text-align:right;\"> 39.94974 </td>\n   <td style=\"text-align:right;\"> -75.18097 </td>\n   <td style=\"text-align:right;\"> 5,174 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,359 </td>\n   <td style=\"text-align:right;\"> 39.94888 </td>\n   <td style=\"text-align:right;\"> -75.16978 </td>\n   <td style=\"text-align:right;\"> 4,681 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,185 </td>\n   <td style=\"text-align:right;\"> 39.95169 </td>\n   <td style=\"text-align:right;\"> -75.15888 </td>\n   <td style=\"text-align:right;\"> 4,670 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,028 </td>\n   <td style=\"text-align:right;\"> 39.94061 </td>\n   <td style=\"text-align:right;\"> -75.14958 </td>\n   <td style=\"text-align:right;\"> 4,607 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,020 </td>\n   <td style=\"text-align:right;\"> 39.94855 </td>\n   <td style=\"text-align:right;\"> -75.19007 </td>\n   <td style=\"text-align:right;\"> 4,556 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,022 </td>\n   <td style=\"text-align:right;\"> 39.95472 </td>\n   <td style=\"text-align:right;\"> -75.18323 </td>\n   <td style=\"text-align:right;\"> 4,475 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,066 </td>\n   <td style=\"text-align:right;\"> 39.94561 </td>\n   <td style=\"text-align:right;\"> -75.17348 </td>\n   <td style=\"text-align:right;\"> 4,353 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,059 </td>\n   <td style=\"text-align:right;\"> 39.96244 </td>\n   <td style=\"text-align:right;\"> -75.16121 </td>\n   <td style=\"text-align:right;\"> 4,265 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,063 </td>\n   <td style=\"text-align:right;\"> 39.94633 </td>\n   <td style=\"text-align:right;\"> -75.16980 </td>\n   <td style=\"text-align:right;\"> 4,230 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,161 </td>\n   <td style=\"text-align:right;\"> 39.95486 </td>\n   <td style=\"text-align:right;\"> -75.18091 </td>\n   <td style=\"text-align:right;\"> 4,223 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,101 </td>\n   <td style=\"text-align:right;\"> 39.94295 </td>\n   <td style=\"text-align:right;\"> -75.15955 </td>\n   <td style=\"text-align:right;\"> 4,183 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,054 </td>\n   <td style=\"text-align:right;\"> 39.96250 </td>\n   <td style=\"text-align:right;\"> -75.17420 </td>\n   <td style=\"text-align:right;\"> 4,117 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,030 </td>\n   <td style=\"text-align:right;\"> 39.93935 </td>\n   <td style=\"text-align:right;\"> -75.15716 </td>\n   <td style=\"text-align:right;\"> 3,986 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,362 </td>\n   <td style=\"text-align:right;\"> 39.94816 </td>\n   <td style=\"text-align:right;\"> -75.16226 </td>\n   <td style=\"text-align:right;\"> 3,965 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,061 </td>\n   <td style=\"text-align:right;\"> 39.95425 </td>\n   <td style=\"text-align:right;\"> -75.17761 </td>\n   <td style=\"text-align:right;\"> 3,716 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,057 </td>\n   <td style=\"text-align:right;\"> 39.96439 </td>\n   <td style=\"text-align:right;\"> -75.17987 </td>\n   <td style=\"text-align:right;\"> 3,668 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,296 </td>\n   <td style=\"text-align:right;\"> 39.95134 </td>\n   <td style=\"text-align:right;\"> -75.16758 </td>\n   <td style=\"text-align:right;\"> 3,665 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Loading Philadelphia Census Data\n\nWe'll get census tract data to add demographic context to our stations.\n\n\n::: {.cell}\n\n:::\n\n\n## Map Philadelphia Context\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab_5_files/figure-html/map_philly-1.png){width=672}\n:::\n:::\n\n\nNote: WGS84 is a geographic (angular) coordinate system measured in degrees of latitude and longitude, not in meters or feet. Distance calculations and buffers in WGS84 are inaccurate because a degree of longitude covers a very different physical distance depending on latitude. To compute meaningful spatial distances or buffers in Philadelphia, the data should first be reprojected to a projected CRS with linear units, such as Pennsylvania State Plane South (EPSG: 2272, in feet) or UTM Zone 18N (EPSG: 32618, in meters). Only then will buffer distances and distance calculations reflect true on-the-ground measurements.\n\n## Joining Census Data to Stations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create sf object for stations \nstations_sf <- indego3 %>%   \n  distinct(start_station, start_lat, start_lon) %>%   \n  filter(!is.na(start_lat), !is.na(start_lon)) %>%   \n  st_as_sf(coords = c(\"start_lon\", \"start_lat\"), crs = 4326)  \n\n# Spatial join to get census tract for each station \nstations_census <- st_join(stations_sf, philly_census, left = TRUE) %>%\n  st_drop_geometry()  \n\n# Look at the result - investigate whether all of the stations joined to census data -- according to the map above there are stations in non-residential tracts.\n\nstations_for_map <- indego3 %>%   \n  distinct(start_station, start_lat, start_lon) %>%   \n  filter(!is.na(start_lat), !is.na(start_lon)) %>%   \n  left_join(     \n    stations_census %>% \n      select(start_station, Med_Inc),     \n      by = \"start_station\"   \n  ) %>%   \n  mutate(has_census = !is.na(Med_Inc))  \n\n# Add back to trip data \nindego_census <- indego3 %>%   \n  left_join(     \n    stations_census %>%        \n      select(start_station, Med_Inc, Percent_Taking_Transit,\n             Percent_White, Total_Pop),     \n    by = \"start_station\"   \n  )   \n\n# Prepare data for visualization \n\nstations_for_map <- indego3 %>%   \n  distinct(start_station, start_lat, start_lon) %>%   \n  filter(!is.na(start_lat), !is.na(start_lon)) %>%   \n  left_join(     \n    stations_census %>% \n      select(start_station, Med_Inc),     \n    by = \"start_station\"   \n    ) %>%   \n  mutate(has_census = !is.na(Med_Inc))  \n\n# Create the map showing problem stations \n\nggplot() +   \n  geom_sf(data = philly_census, aes(fill = Med_Inc), color = \"white\", size = 0.1) +   \n  scale_fill_viridis(     \n    option = \"viridis\",     \n    name = \"Median\\nIncome\",     \n    labels = scales::dollar,     \n    na.value = \"grey90\"   \n    ) +   \n  # Stations with census data (small grey dots)   \n  geom_point(     \n    data = stations_for_map %>% \n      filter(has_census),     \n    aes(x = start_lon, y = start_lat),     \n    color = \"grey30\", size = 1, alpha = 0.6   \n    ) +   \n  # Stations WITHOUT census data (red X marks the spot)   \n  geom_point(     \n    data = stations_for_map %>% \n      filter(!has_census),     \n    aes(x = start_lon, y = start_lat),     \n    color = \"red\", size = 1, shape = 4, stroke = 1.5   \n    ) +   \n  labs(     \n    title = \"Philadelphia Median Household Income by Census Tract\",   \n    subtitle = \"Indego stations shown (RED = no census data match)\",  \n    caption = \"Red X marks indicate stations that didn't join to census tracts\"   \n    ) +   \n  mapTheme   \n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/join_census_to_stations-1.png){width=672}\n:::\n:::\n\n\n## Dealing with missing data\n\nFor this example, we are going to remove them, this is not necessarily the right way to do things always, but for the sake of simplicity, we are narrowing our scope to only stations in residential neighborhoods. We might opt to create a separate model for non-residential stations..\n\n\n::: {.cell}\n\n:::\n\n\n## Weather Data\n\nWeather significantly affects bike share demand! Let's get hourly weather for Philadelphia.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  Temperature    Precipitation         Wind_Speed    \n Min.   :57.00   Min.   :0.0000000   Min.   : 0.000  \n 1st Qu.:70.00   1st Qu.:0.0000000   1st Qu.: 4.000  \n Median :76.00   Median :0.0000000   Median : 6.000  \n Mean   :75.94   Mean   :0.0008342   Mean   : 6.218  \n 3rd Qu.:81.00   3rd Qu.:0.0000000   3rd Qu.: 8.000  \n Max.   :98.00   Max.   :0.1000000   Max.   :25.000  \n```\n\n\n:::\n:::\n\n\n## Visualize Weather Patterns\n\nPhiladelphia in Q3 runs hot — temperatures ranged from 57°F to 98°F, with a median of 76°F. The smoothed trend shows a gradual cooling from August into September as the season shifts toward early fall. Precipitation was rare and generally light, with a mean of less than 0.001 inches per hour. These summer conditions matter for modeling: high heat likely suppresses ridership on the hottest days.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab_5_files/figure-html/visualize-weather-1.png){width=672}\n:::\n:::\n\n\n## SPACE-TIME PANEL\n\n### Aggregating Trips to Station-Hour Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count trips by station-hour \ntrips_panel_3 <- indego3_census %>%   \n  group_by(interval60, start_station, start_lat, start_lon,            \n           Med_Inc, Percent_Taking_Transit, Percent_White, Total_Pop) %>%\n  summarize(Trip_Count = n()) %>%  \n  ungroup() \n\n# How many station-hour observations? \nnrow(trips_panel_3)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 214178\n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique stations? \nlength(unique(trips_panel_3$start_station))  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 263\n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique hours? \nlength(unique(trips_panel_3$interval60))  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2208\n```\n\n\n:::\n\n```{.r .cell-code}\nhist(trips_panel_3$Trip_Count)\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/aggregate-trips-1.png){width=672}\n:::\n:::\n\n\n### Complete Panel Structure\n\nNot every station has trips every hour. We need a **complete panel** where every station-hour combination exists (even if Trip_Count = 0).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate expected panel size \nn_stations <- length(unique(trips_panel_3$start_station)) \nn_hours <- length(unique(trips_panel_3$interval60)) \nexpected_rows <- n_stations * n_hours  \n\ncat(\"Expected panel rows:\", format(expected_rows, big.mark = \",\"), \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpected panel rows: 580,704 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Current rows:\", format(nrow(trips_panel_3), big.mark = \",\"), \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCurrent rows: 214,178 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Missing rows:\", format(expected_rows - nrow(trips_panel_3), big.mark = \",\"), \"\\n\")  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing rows: 366,526 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Create complete panel \nstudy_panel_3 <- expand_grid(   \n  interval60 = unique(trips_panel_3$interval60),   \n  start_station = unique(trips_panel_3$start_station) \n) %>%   \n  # Join trip counts   \n  left_join(trips_panel_3 %>%                \n              select(interval60, start_station, Trip_Count),             \n            by = c(\"interval60\", \"start_station\")) %>%   \n  # Replace NA trip counts with 0   \n  mutate(Trip_Count = replace_na(Trip_Count, 0))  \n\n\nhist(study_panel_3$Trip_Count)  \n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/complete-panel-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Fill in station attributes (they're the same for all hours)\nstation_attributes_3 <- trips_panel_3 %>%   \n  group_by(start_station) %>%   \n  summarize(     \n    start_lat = first(start_lat),     \n    start_lon = first(start_lon),     \n    Med_Inc = first(Med_Inc),     \n    Percent_Taking_Transit = first(Percent_Taking_Transit),     \n    Percent_White = first(Percent_White),     \n    Total_Pop = first(Total_Pop)   \n    )  \n\n\nstudy_panel_3 <- study_panel_3 %>%   \n  left_join(station_attributes_3, by = \"start_station\")  \n\n\n# Verify we have complete panel \n\ncat(\"Complete panel rows:\", format(nrow(study_panel_3), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComplete panel rows: 580,704 \n```\n\n\n:::\n:::\n\n\n### Time Features\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy_panel_3 <- study_panel_3 %>%  \n  mutate(     \n    week = week(interval60),     \n    month = month(interval60, label = TRUE),     \n    dotw = wday(interval60, label = TRUE),     \n    hour = hour(interval60),     \n    date = as.Date(interval60),     \n    weekend = ifelse(dotw %in% c(\"Sat\", \"Sun\"), 1, 0),     \n    rush_hour = ifelse(hour %in% c(7, 8, 9, 16, 17, 18), 1, 0)   \n    )  \n\n\nhead(study_panel_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 16\n  interval60          start_station Trip_Count start_lat start_lon Med_Inc\n  <dttm>                      <dbl>      <int>     <dbl>     <dbl>   <dbl>\n1 2025-07-01 00:00:00          3058          1      40.0     -75.2   89669\n2 2025-07-01 00:00:00          3061          1      40.0     -75.2   86293\n3 2025-07-01 00:00:00          3078          1      40.0     -75.2   90980\n4 2025-07-01 00:00:00          3100          1      39.9     -75.2   95745\n5 2025-07-01 00:00:00          3114          1      39.9     -75.2  102969\n6 2025-07-01 00:00:00          3160          1      40.0     -75.2   36574\n# ℹ 10 more variables: Percent_Taking_Transit <dbl>, Percent_White <dbl>,\n#   Total_Pop <dbl>, week <dbl>, month <ord>, dotw <ord>, hour <int>,\n#   date <date>, weekend <dbl>, rush_hour <dbl>\n```\n\n\n:::\n:::\n\n\n### Weather Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy_panel_3 <- study_panel_3 %>%   \n  left_join(weather_complete, by = \"interval60\")  \n\n\n# Check for missing values \nsummary(study_panel_3 %>% select(Trip_Count, Temperature, Precipitation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Trip_Count       Temperature    Precipitation   \n Min.   : 0.0000   Min.   :57.00   Min.   :0.0000  \n 1st Qu.: 0.0000   1st Qu.:70.00   1st Qu.:0.0000  \n Median : 0.0000   Median :76.00   Median :0.0000  \n Mean   : 0.7548   Mean   :75.94   Mean   :0.0008  \n 3rd Qu.: 1.0000   3rd Qu.:81.00   3rd Qu.:0.0000  \n Max.   :22.0000   Max.   :98.00   Max.   :0.1000  \n                   NA's   :6312    NA's   :6312    \n```\n\n\n:::\n:::\n\n\n## TEMPORAL LAG VARIABLES\n\nThe key innovation for space-time prediction: **past demand predicts future demand**.\n\n### Why Temporal Lags?\n\nIf there were 15 bike trips from Station A at 8:00 AM, there will probably be \\~15 trips at 9:00 AM. We can use this temporal persistence to improve predictions.\n\n**Note:** We still can't use spatial lags in prediction. Temporal lags are different because time moves in one direction - past predicts the future, but the future does not predict the past. Spatial lags are non-directional and create circular prediction logic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort by station and time \nstudy_panel_3 <- study_panel_3 %>%   \n  arrange(start_station, interval60)  \n\n# Create lag variables WITHIN each station \nstudy_panel_3 <- study_panel_3 %>%   \n  group_by(start_station) %>%   \n  mutate(     \n    lag1Hour = lag(Trip_Count, 1),     \n    lag2Hours = lag(Trip_Count, 2),     \n    lag3Hours = lag(Trip_Count, 3),     \n    lag12Hours = lag(Trip_Count, 12),     \n    lag1day = lag(Trip_Count, 24)   \n    ) %>%   \n  ungroup()  \n\n# Remove rows with NA lags (first 24 hours for each statio\nstudy_panel_complete_3 <- study_panel_3%>%   \n  filter(!is.na(lag1day))  \n\ncat(\"Rows after removing NA lags:\", format(nrow(study_panel_complete_3), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows after removing NA lags: 574,392 \n```\n\n\n:::\n:::\n\n\n### Visualizing Lag Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sample one station to visualize \nexample_station <- study_panel_complete_3 %>%   \n  filter(start_station == first(start_station)) %>%   \n  head(168)  # One week  \n\n# Plot actual vs lagged demand \nggplot(example_station, aes(x = interval60)) +   \n  geom_line(aes(y = Trip_Count, color = \"Current\"), linewidth = 1) +\n  geom_line(aes(y = lag1Hour, color = \"1 Hour Ago\"), linewidth = 1, alpha = 0.7) +   \n  geom_line(aes(y = lag1day, color = \"24 Hours Ago\"), linewidth = 1, alpha = 0.7) +   \n  scale_color_manual(values = c(     \n    \"Current\" = \"#08519c\",     \n    \"1 Hour Ago\" = \"#3182bd\",     \n    \"24 Hours Ago\" = \"#6baed6\"   )) +   \n  labs(     \n    title = \"Temporal Lag Patterns at One Station\",     \n    subtitle = \"Past demand predicts future demand\",     \n    x = \"Date-Time\",     \n    y = \"Trip Count\",     \n    color = \"Time Period\"   \n    ) +   \n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/lag_correlations-1.png){width=672}\n:::\n:::\n\n\n## TEMPORAL TRAIN/TEST SPLIT\n\n### Why Temporal Validation Matters\n\nIn real operations, at 6:00 AM on March 15, we need to predict demand for March 15-31. We have data from Jan 1 - March 14, but NOT from March 15-31 (it hasn't happened yet!).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Split by week \n# Q3 has weeks 1-13 (July-Sept) \n# Train on weeks 26-35 (July 1 - early Sept) \n# Test on weeks 36-39 (rest of Sept)  \n\n# Which stations have trips in BOTH early and late periods? \nearly_stations_3 <- study_panel_complete_3 %>%   \n  dplyr::filter(week  >= 26 & week <= 35) %>%   \n  dplyr::filter(Trip_Count > 0) %>%   \n  dplyr::distinct(start_station) %>%   \n  dplyr::pull(start_station)  \n\nlate_stations_3 <- study_panel_complete_3 %>%   \n  filter(week >= 36 & week <= 39) %>%   \n  filter(Trip_Count > 0) %>%   \n  distinct(start_station) %>%   \n  pull(start_station)  \n\n# Keep only stations that appear in BOTH periods \ncommon_stations_3 <- intersect(early_stations_3, late_stations_3)   \n\n# Filter panel to only common stations \nstudy_panel_complete_3 <- study_panel_complete_3 %>%   \n  filter(start_station %in% common_stations_3)  \n\n# NOW create train/test split \ntrain_b <- study_panel_complete_3 %>%   \n  filter(week >= 26 & week <= 35)\n\ntest_b <- study_panel_complete_3 %>%   \n  filter(week >= 36 & week <= 39)  \n\ncat(\"Training observations:\", format(nrow(train_b), big.mark = \",\"), \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining observations: 397,656 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Testing observations:\", format(nrow(test_b), big.mark = \",\"), \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting observations: 176,736 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Training date range:\", min(train_b$date), \"to\", max(train_b$date), \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining date range: 20271 to 20333 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Testing date range:\", min(test_b$date), \"to\", max(test_b$date), \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting date range: 20334 to 20361 \n```\n\n\n:::\n:::\n\n\nWe'll build 5 models with increasing complexity to see what improves predictions.\n\n### Model 1: Baseline (Time + Weather)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create day of week factor with treatment (dummy) coding \n\ntrain_b <- train_b %>%   \n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\"))) \n\n# Set contrasts to treatment coding (dummy variables) \ncontrasts(train_b$dotw_simple) <- contr.treatment(7)  \n\n# Now run the model \nmodel1_b <- lm(   \n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation,\n  data = train_b \n  )  \n\nsummary(model1_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation, data = train_b)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.7607 -0.7740 -0.2103  0.1990 21.0953 \n\nCoefficients:\n                    Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)        0.5550150  0.0300177  18.490 < 0.0000000000000002 ***\nas.factor(hour)1  -0.0826330  0.0138397  -5.971 0.000000002363946822 ***\nas.factor(hour)2  -0.1524551  0.0138489 -11.008 < 0.0000000000000002 ***\nas.factor(hour)3  -0.2120619  0.0138853 -15.272 < 0.0000000000000002 ***\nas.factor(hour)4  -0.2120367  0.0139236 -15.229 < 0.0000000000000002 ***\nas.factor(hour)5  -0.0924856  0.0139487  -6.630 0.000000000033514919 ***\nas.factor(hour)6   0.1475087  0.0139924  10.542 < 0.0000000000000002 ***\nas.factor(hour)7   0.4252906  0.0140113  30.353 < 0.0000000000000002 ***\nas.factor(hour)8   0.8395960  0.0140551  59.736 < 0.0000000000000002 ***\nas.factor(hour)9   0.5728099  0.0140648  40.726 < 0.0000000000000002 ***\nas.factor(hour)10  0.4557683  0.0140421  32.457 < 0.0000000000000002 ***\nas.factor(hour)11  0.5268346  0.0139489  37.769 < 0.0000000000000002 ***\nas.factor(hour)12  0.6107369  0.0138516  44.091 < 0.0000000000000002 ***\nas.factor(hour)13  0.6670252  0.0138149  48.283 < 0.0000000000000002 ***\nas.factor(hour)14  0.7402386  0.0138191  53.566 < 0.0000000000000002 ***\nas.factor(hour)15  0.8543935  0.0138536  61.673 < 0.0000000000000002 ***\nas.factor(hour)16  1.0724723  0.0139071  77.117 < 0.0000000000000002 ***\nas.factor(hour)17  1.4064254  0.0139605 100.743 < 0.0000000000000002 ***\nas.factor(hour)18  1.1221752  0.0140032  80.137 < 0.0000000000000002 ***\nas.factor(hour)19  0.8972548  0.0140107  64.041 < 0.0000000000000002 ***\nas.factor(hour)20  0.6166802  0.0139991  44.051 < 0.0000000000000002 ***\nas.factor(hour)21  0.4263710  0.0139337  30.600 < 0.0000000000000002 ***\nas.factor(hour)22  0.2827427  0.0138773  20.374 < 0.0000000000000002 ***\nas.factor(hour)23  0.1443094  0.0138245  10.439 < 0.0000000000000002 ***\ndotw_simple2       0.1118817  0.0074558  15.006 < 0.0000000000000002 ***\ndotw_simple3       0.0467614  0.0074545   6.273 0.000000000354768852 ***\ndotw_simple4       0.0784867  0.0074920  10.476 < 0.0000000000000002 ***\ndotw_simple5       0.0816654  0.0074696  10.933 < 0.0000000000000002 ***\ndotw_simple6       0.0031623  0.0074809   0.423                0.673    \ndotw_simple7      -0.0611977  0.0074606  -8.203 0.000000000000000235 ***\nTemperature       -0.0042308  0.0003539 -11.953 < 0.0000000000000002 ***\nPrecipitation     -4.2828242  0.4084060 -10.487 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.256 on 397624 degrees of freedom\nMultiple R-squared:  0.1087,\tAdjusted R-squared:  0.1086 \nF-statistic:  1565 on 31 and 397624 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\nModel 1 uses Monday as the reference category, so all day-of-week coefficients represent the change in expected trips per station-hour relative to a typical Monday. The hourly coefficients use midnight (hour 0) as the baseline.\n\n**Day-of-week effects:**\n\nAll weekdays (Tuesday–Friday) have positive coefficients relative to Monday, suggesting slightly higher ridership mid-week, with Tuesday showing the largest boost (+0.112). Saturday is statistically indistinguishable from Monday (p = 0.67), while Sunday shows a significant negative effect (−0.061), meaning Sundays have the lowest ridership of the week. This likely reflects the commuter-heavy nature of Indego demand — Monday through Friday outperform the weekend.\n\n**Hourly effects:**\n\nThe hour coefficients tell a clear story of commuter demand. The model peaks at hour 17 (+1.41 trips relative to midnight), followed by hour 18 (+1.12) and hour 8 (+0.84), tracing the classic morning and evening rush hour pattern. Demand is lowest between midnight and 5 AM, then builds sharply from hour 6 onward. Despite capturing these clear structural patterns, Model 1 only explains about 11% of variance in trip counts (R² = 0.109), indicating that time and weather alone are far from sufficient.\n\n**Weather effects:**\n\nBoth temperature and precipitation have negative, statistically significant coefficients. Each additional degree Fahrenheit reduces expected trips by about 0.004, and an inch of rain reduces demand by \\~4.3 trips per station-hour — a large effect that reflects how strongly precipitation discourages cycling.\n\n### Model 2: Temporal Lags\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2_b <- lm(   \n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +     lag1Hour + lag3Hours + lag1day,   \n   data = train_b\n  )  \n\nsummary(model2_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation + lag1Hour + lag3Hours + lag1day, data = train_b)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.0431 -0.5262 -0.1495  0.1985 17.0478 \n\nCoefficients:\n                    Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)        0.2333499  0.0261594   8.920 < 0.0000000000000002 ***\nas.factor(hour)1  -0.0114037  0.0120498  -0.946             0.343957    \nas.factor(hour)2  -0.0220637  0.0120636  -1.829             0.067408 .  \nas.factor(hour)3  -0.0347400  0.0121031  -2.870             0.004101 ** \nas.factor(hour)4  -0.0092455  0.0121438  -0.761             0.446457    \nas.factor(hour)5   0.0802272  0.0121703   6.592      0.0000000000434 ***\nas.factor(hour)6   0.2307287  0.0122213  18.879 < 0.0000000000000002 ***\nas.factor(hour)7   0.3676258  0.0122566  29.994 < 0.0000000000000002 ***\nas.factor(hour)8   0.5828786  0.0123394  47.237 < 0.0000000000000002 ***\nas.factor(hour)9   0.2557703  0.0123195  20.762 < 0.0000000000000002 ***\nas.factor(hour)10  0.2059620  0.0122513  16.811 < 0.0000000000000002 ***\nas.factor(hour)11  0.2355785  0.0121748  19.350 < 0.0000000000000002 ***\nas.factor(hour)12  0.3113380  0.0120920  25.747 < 0.0000000000000002 ***\nas.factor(hour)13  0.3490276  0.0120695  28.918 < 0.0000000000000002 ***\nas.factor(hour)14  0.3808720  0.0120810  31.526 < 0.0000000000000002 ***\nas.factor(hour)15  0.4387024  0.0121250  36.182 < 0.0000000000000002 ***\nas.factor(hour)16  0.5649168  0.0122047  46.287 < 0.0000000000000002 ***\nas.factor(hour)17  0.7440528  0.0123211  60.389 < 0.0000000000000002 ***\nas.factor(hour)18  0.4455279  0.0123526  36.068 < 0.0000000000000002 ***\nas.factor(hour)19  0.3283896  0.0123019  26.694 < 0.0000000000000002 ***\nas.factor(hour)20  0.1422597  0.0122831  11.582 < 0.0000000000000002 ***\nas.factor(hour)21  0.1091051  0.0121756   8.961 < 0.0000000000000002 ***\nas.factor(hour)22  0.0799153  0.0121004   6.604      0.0000000000400 ***\nas.factor(hour)23  0.0465330  0.0120385   3.865             0.000111 ***\ndotw_simple2       0.0573785  0.0064929   8.837 < 0.0000000000000002 ***\ndotw_simple3      -0.0070949  0.0064918  -1.093             0.274442    \ndotw_simple4       0.0215023  0.0065240   3.296             0.000981 ***\ndotw_simple5       0.0181487  0.0065052   2.790             0.005273 ** \ndotw_simple6      -0.0402855  0.0065157  -6.183      0.0000000006302 ***\ndotw_simple7      -0.0613107  0.0064966  -9.437 < 0.0000000000000002 ***\nTemperature       -0.0028445  0.0003082  -9.231 < 0.0000000000000002 ***\nPrecipitation     -1.8011789  0.3557161  -5.064      0.0000004117475 ***\nlag1Hour           0.2494052  0.0015244 163.605 < 0.0000000000000002 ***\nlag3Hours          0.1200577  0.0014804  81.096 < 0.0000000000000002 ***\nlag1day            0.2831468  0.0015010 188.635 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.094 on 397621 degrees of freedom\nMultiple R-squared:  0.3246,\tAdjusted R-squared:  0.3245 \nF-statistic:  5620 on 34 and 397621 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\nYes, adding temporal lag variables substantially improved model fit. Model 1 (time + weather only) achieved an R² of 0.109, while Model 2 (adding lag1Hour, lag3Hours, and lag1day) jumped to R² = 0.325, nearly tripling explanatory power. This makes intuitive sense: past demand is one of the strongest predictors of current demand at a given station.\n\nThe lag1day coefficient (0.283) is especially large, capturing the strong same-hour-yesterday pattern that is, if a station was busy at 8 AM yesterday, it's likely busy at 8 AM today. The 1-hour lag (0.249) captures short-term temporal autocorrelation, while the 3-hour lag (0.120) adds additional information about recent trends. The MAE also dropped from 0.88 to 0.75 trips, confirming that temporal lags meaningfully improve predictive accuracy on the test set.\n\n### Model 3: Demographics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3_b <- lm(   \n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +     lag1Hour + lag3Hours + lag1day +     \n    Med_Inc + Percent_Taking_Transit + Percent_White,   \n  data = train_b)  \n# Show only the new demographic coefficients and fit stats\n\ncoefs <- summary(model3_b)$coefficients\nnew_vars <- c(\"Med_Inc\", \"Percent_Taking_Transit\", \"Percent_White\")\nkable(coefs[new_vars, ], digits = 6,\n      caption = \"Model 3: New Demographic Coefficients\") %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model 3: New Demographic Coefficients</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">  </th>\n   <th style=\"text-align:right;\"> Estimate </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> t value </th>\n   <th style=\"text-align:right;\"> Pr(&gt;&amp;#124;t&amp;#124;) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Med_Inc </td>\n   <td style=\"text-align:right;\"> 0.000001 </td>\n   <td style=\"text-align:right;\"> 0.000000 </td>\n   <td style=\"text-align:right;\"> 20.09832 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Percent_Taking_Transit </td>\n   <td style=\"text-align:right;\"> -0.002730 </td>\n   <td style=\"text-align:right;\"> 0.000199 </td>\n   <td style=\"text-align:right;\"> -13.74604 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Percent_White </td>\n   <td style=\"text-align:right;\"> 0.001928 </td>\n   <td style=\"text-align:right;\"> 0.000100 </td>\n   <td style=\"text-align:right;\"> 19.33031 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\ncat(\"Model 3 R-squared:\", summary(model3_b)$r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 3 R-squared: 0.3308511 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 3 Adj R-squared:\", summary(model3_b)$adj.r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 3 Adj R-squared: 0.3307888 \n```\n\n\n:::\n:::\n\n\nAdding neighborhood demographic variables from the American Community Survey produces a modest but statistically meaningful improvement, with R² rising from 0.325 to 0.331. All three demographic variables are highly significant. Median income has a small positive effect (coefficient \\~0.0000013), indicating that stations in wealthier tracts see slightly higher demand even after controlling for time and recent ridership. `Percent_Taking_Transit` has a negative coefficient (−0.0027), which may seem counterintuitive but likely reflects that high-transit neighborhoods tend to be lower-income areas with less Indego adoption. `Percent_White` has a positive coefficient (+0.0019), capturing the structural reality that Indego's station network and ridership skews toward whiter, higher-income neighborhoods — a pattern the model learns from the data rather than corrects. The MAE remains at 0.75, essentially unchanged from Model 2, suggesting that demographic variables improve statistical fit but do not dramatically change prediction accuracy at the station-hour level.\n\n### Model 4: Station Fixed Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4_b <- lm(   \n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day +     \n    Med_Inc + Percent_Taking_Transit + Percent_White +     \n    as.factor(start_station),   \n  data = train_b )  \n\n# Summary too long with all station dummies, just show key metrics \n\ncat(\"Model 4 R-squared:\", summary(model4_b)$r.squared, \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 4 R-squared: 0.3603716 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 4 Adj R-squared:\", summary(model4_b)$adj.r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 4 Adj R-squared: 0.3598952 \n```\n\n\n:::\n:::\n\n\nStation fixed effects account for the baseline, time-invariant differences in demand across stations — the fact that Station 3,010 (the busiest station in Q3 with 7,716 trips) will simply always attract more riders than a quieter neighborhood station, regardless of the hour or weather. Adding these dummies pushes R² to 0.360, a meaningful jump from 0.331. Essentially, each station gets its own intercept, absorbing any unobserved station-level characteristics (proximity to transit, land use, dock capacity) that the demographic variables couldn't fully capture.\n\n### Model 5: Add Rush Hour Interaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel5_b <- lm(   \n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +     lag1Hour + lag3Hours + lag1day + rush_hour + as.factor(month) +     \n    Med_Inc + Percent_Taking_Transit + Percent_White +     \n    as.factor(start_station) +     \n    rush_hour * weekend,  # Rush hour effects different on weekends   \n  data = train_b )  \n\ncat(\"Model 5 R-squared:\", summary(model5_b)$r.squared, \"\\n\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 5 R-squared: 0.3641351 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 5 Adj R-squared:\", summary(model5_b)$adj.r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 5 Adj R-squared: 0.3636566 \n```\n\n\n:::\n:::\n\n\nModel 5 adds a `rush_hour × weekend` interaction and month fixed effects. The interaction allows the model to learn that the 7–9 AM and 4–6 PM demand spikes that define weekday ridership essentially disappear on weekends — weekenders don't commute, so rush hour is not a meaningful concept for them. Month fixed effects capture any residual within-quarter seasonality (July vs. August vs. September patterns) not already absorbed by the weekly and hourly features. Together these additions bring R² to 0.364, a marginal improvement over Model 4. The gains are real but small, suggesting the model is approaching a ceiling with this feature set — the next meaningful improvements require new data types (events, points of interest, real-time weather) rather than more clever combinations of existing variables.\n\n## MODEL EVALUATION\n\n### Calculate Predictions and MAE\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get predictions on test set  \n\n# Create day of week factor with treatment (dummy) coding \ntest_b <- test_b %>%   \n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\")))  \n\n# Set contrasts to treatment coding (dummy variables) \ncontrasts(test_b$dotw_simple) <- contr.treatment(7)  \n\ntest_b <- test_b %>%   \n  mutate(     \n    pred1 = predict(model1_b, newdata = test_b),     \n    pred2 = predict(model2_b, newdata = test_b),     \n    pred3 = predict(model3_b, newdata = test_b),     \n    pred4 = predict(model4_b, newdata = test_b),     \n    pred5 = predict(model5_b, newdata = test_b)   \n    )  \n# Calculate MAE for each model \nmae_results_q3 <- data.frame(   \n  Model = c(     \n    \"1. Time + Weather\",     \n    \"2. + Temporal Lags\",     \n    \"3. + Demographics\",     \n    \"4. + Station FE\",     \n    \"5. + Rush Hour Interaction\"   \n    ),   \n  MAE = c(     \n    mean(abs(test_b$Trip_Count - test_b$pred1), na.rm = TRUE),     \n    mean(abs(test_b$Trip_Count - test_b$pred2), na.rm = TRUE),     \n    mean(abs(test_b$Trip_Count - test_b$pred3), na.rm = TRUE),     \n    mean(abs(test_b$Trip_Count - test_b$pred4), na.rm = TRUE),     \n    mean(abs(test_b$Trip_Count - test_b$pred5), na.rm = TRUE)   \n    ) \n  )  \n\nkable(mae_results_q3,        \n      digits = 2,       \n      caption = \"Mean Absolute Error by Model (Test Set) for Q3\",       \n      col.names = c(\"Model\", \"MAE (trips)\")) %>%   \n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Mean Absolute Error by Model (Test Set) for Q3</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> MAE (trips) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1. Time + Weather </td>\n   <td style=\"text-align:right;\"> 0.88 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2. + Temporal Lags </td>\n   <td style=\"text-align:right;\"> 0.75 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3. + Demographics </td>\n   <td style=\"text-align:right;\"> 0.75 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 4. + Station FE </td>\n   <td style=\"text-align:right;\"> 0.74 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5. + Rush Hour Interaction </td>\n   <td style=\"text-align:right;\"> 0.74 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n### Visualize Model Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mae_results_q3, aes(x = reorder(Model, -MAE), y = MAE)) +   \n  geom_col(fill = \"#3182bd\", alpha = 0.8) +   \n  geom_text(aes(label = round(MAE, 2)), vjust = -0.5) +   \n  labs(     \n    title = \"Model Performance Comparison for Q3\",     \n    subtitle = \"Lower MAE = Better Predictions\",     \n    x = \"Model\",     \n    y = \"Mean Absolute Error (trips)\"   \n    ) +   \n  plotTheme +   \n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/compare_models-1.png){width=672}\n:::\n:::\n\n\nTemporal lag variables (Model 2) delivered by far the largest single improvement, dropping MAE from 0.88 to 0.75 trips and nearly tripling R². Adding demographics (Model 3) and station fixed effects (Model 4) each contributed smaller but meaningful gains, Model 4 reached R² = 0.360, suggesting that station-level baseline differences in demand matter.\n\nThe rush hour interaction in Model 5 added marginal improvement (R² = 0.364), capturing the fact that rush hour effects behave differently on weekends. Overall, the progression illustrates a classic modeling insight: capturing temporal autocorrelation through lags is the highest-value feature in this type of space-time demand prediction problem.\n\n# Part 2: Error Analysis\n\n### SPACE-TIME ERROR ANALYSIS\n\n### Observed vs. Predicted\n\nLet's use our best model (Model 2) for error analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_b <- test_b %>%   \n  mutate(     \n    error = Trip_Count - pred2,     \n    abs_error = abs(error),     \n    time_of_day = case_when(       \n      hour < 7 ~ \"Overnight\",       \n      hour >= 7 & hour < 10 ~ \"AM Rush\",       \n      hour >= 10 & hour < 15 ~ \"Mid-Day\",       \n      hour >= 15 & hour <= 18 ~ \"PM Rush\",       \n      hour > 18 ~ \"Evening\"     \n      )   \n    )  \n\n# Scatter plot by time and day type \nggplot(test_b, aes(x = Trip_Count, y = pred2)) +   \n  geom_point(alpha = 0.2, color = \"#3182bd\") +   \n  geom_abline(slope = 1, intercept = 0, color = \"red\", linewidth = 1) + \n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkgreen\") +   \n  facet_grid(weekend ~ time_of_day) +   \n  labs(     \n    title = \"Observed vs. Predicted Bike Trips\",     \n    subtitle = \"Model 2 performance by time period\",     \n    x = \"Observed Trips\",     \n    y = \"Predicted Trips\",     \n    caption = \"Red line = perfect predictions; Green line = actual model fit\"   ) +   \n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/obs_vs_pred-1.png){width=672}\n:::\n:::\n\n\nThe model struggles across the board with high-demand observations. The green fit line falls well below the red perfect-prediction line in every panel, indicating systematic underprediction when actual trip counts are high.\n\nThis problem is most severe during **AM Rush and PM Rush on weekdays**, where observed counts reach 15–20 trips per station-hour but predictions plateau far below. The model performs best during **Overnight** hours (row 0), where demand is low, stable, and near zero.\n\nWeekend panels (row 1) show consistently flatter green lines than their weekday counterparts, meaning the model generalizes poorly to weekend leisure patterns regardless of time of day, the commute-based temporal lags do not transfer well.\n\nThere is also a visible zero-inflation problem: many observations with 0 actual trips receive positive predictions, suggesting a Poisson or hurdle model may be more appropriate for this count data.\n\n## Spatial Error Patterns\n\nWhere are prediction errors clustered in parts of Philadelphia?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MAE by station \n\nstation_errors <- test_b %>%   \n  group_by(start_station, start_lat, start_lon) %>%   \n  summarize(     \n    MAE = mean(abs_error, na.rm = TRUE),     \n    avg_demand = mean(Trip_Count, na.rm = TRUE),     \n    .groups = \"drop\"   \n    ) %>%   \n  filter(!is.na(start_lat), !is.na(start_lon))  \n\n## Create Two Maps Side-by-Side with Proper Legends (sorry these maps are ugly)  \n\n# Calculate station errors \n\nstation_errors <- test_b %>%   \n  filter(!is.na(pred2)) %>%   \n  group_by(start_station, start_lat, start_lon) %>%   \n  summarize(     \n    MAE = mean(abs(Trip_Count - pred2), na.rm = TRUE),     \n    avg_demand = mean(Trip_Count, na.rm = TRUE),     \n    .groups = \"drop\"   \n    ) %>%   \n  filter(!is.na(start_lat), !is.na(start_lon))  \n\n# Map 1: Prediction Errors \np1 <- ggplot() +   \n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.2) +   \n  geom_point(     \n    data = station_errors,     \n    aes(x = start_lon, y = start_lat, color = MAE),     \n    size = 3.5,     \n    alpha = 0.7   \n    ) +   \n  scale_color_viridis(     \n    option = \"plasma\",     \n    name = \"MAE\\n(trips)\",     \n    direction = -1,     \n    breaks = c(0.5, 1.0, 1.5),  # Fewer, cleaner breaks     \n    labels = c(\"0.5\", \"1.0\", \"1.5\")  \n    ) +   \n  labs(title = \"Prediction Errors\",        \n       subtitle = \"Higher in Center City\") +   \n  mapTheme +   \n  theme(     \n    legend.position = \"right\",     \n    legend.title = element_text(size = 10, face = \"bold\"),     \n    legend.text = element_text(size = 9),     \n    plot.title = element_text(size = 14, face = \"bold\"),     \n    plot.subtitle = element_text(size = 10)   ) +   \n  guides(color = guide_colorbar(     \n    barwidth = 1.5,     \n    barheight = 12,     \n    title.position = \"top\",     \n    title.hjust = 0.5   \n    )) \n# Map 2: Average Demand \np2 <- ggplot() +   \n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.2) +   \n  geom_point(     \n    data = station_errors,     \n    aes(x = start_lon, y = start_lat, color = avg_demand),     \n    size = 3.5,     alpha = 0.7   \n    ) +   \n  scale_color_viridis(     \n    option = \"viridis\",     \n    name = \"Avg\\nDemand\",     \n    direction = -1,     \n    breaks = c(0.5, 1.0, 1.5, 2.0, 2.5),  # Clear breaks     \n    labels = c(\"0.5\", \"1.0\", \"1.5\", \"2.0\", \"2.5\")   \n    ) +   \n  labs(title = \"Average Demand\",        \n       subtitle = \"Trips per station-hour\") +   \n  mapTheme +   \n  theme(     \n    legend.position = \"right\",     \n    legend.title = element_text(size = 10, face = \"bold\"),     \n    legend.text = element_text(size = 9),     \n    plot.title = element_text(size = 14, face = \"bold\"),     \n    plot.subtitle = element_text(size = 10)   \n    ) +   \n  guides(color = guide_colorbar(     \n    barwidth = 1.5,     \n    barheight = 12,     \n    title.position = \"top\",     \n    title.hjust = 0.5   ))   \n\n\n\n\n# Map 1: Prediction Errors \n\np1 <- ggplot() +   \n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.1) +   \n  geom_point(     \n    data = station_errors,     \n    aes(x = start_lon, y = start_lat, color = MAE),     \n    size = 3.5,     alpha = 0.7   ) +   \n  scale_color_viridis(     \n    option = \"plasma\",     \n    name = \"MAE (trips)\",     \n    direction = -1,     \n    breaks = c(0.5, 1.0, 1.5),     \n    labels = c(\"0.5\", \"1.0\", \"1.5\")  \n    ) +   \n  labs(title = \"Prediction Errors\") +   \n  mapTheme +   \n  theme(     \n    legend.position = \"bottom\",     \n    legend.title = element_text(size = 10, face = \"bold\"),     \n    legend.text = element_text(size = 9),     \n    plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5)  \n    ) +   \n  guides(color = guide_colorbar(     \n    barwidth = 12,     \n    barheight = 1,     \n    title.position = \"top\",     \n    title.hjust = 0.5   \n    ))  \n\n# Map 2: Average Demand   \np2 <- ggplot() +   \n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.1) +   \n  geom_point(     \n    data = station_errors,     \n    aes(x = start_lon, y = start_lat, color = avg_demand),     \n    size = 3.5,     \n    alpha = 0.7  \n    ) +   \n  scale_color_viridis(     \n    option = \"viridis\",     \n    name = \"Avg Demand (trips/hour)\",     \n    direction = -1,     \n    breaks = c(0.5, 1.0, 1.5, 2.0, 2.5),     \n    labels = c(\"0.5\", \"1.0\", \"1.5\", \"2.0\", \"2.5\")  \n    ) +   \n  labs(title = \"Average Demand\") +   \n  mapTheme +   \n  theme(     \n    legend.position = \"bottom\",     \n    legend.title = element_text(size = 10, face = \"bold\"),     \n    legend.text = element_text(size = 9),     \n    plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5)   \n    ) +   \n  guides(color = guide_colorbar(     \n    barwidth = 12,     \n    barheight = 1,     \n    title.position = \"top\",     \n    title.hjust = 0.5   \n    ))  \n\n# Combine \n\n(p1 | p2) \n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/spatial_errors-1.png){width=672}\n:::\n:::\n\n\nYes, prediction errors are spatially clustered. The highest MAE values concentrate in Center City Philadelphia, particularly around the dense station network near Rittenhouse Square, Old City, and University City, which also corresponds to the highest average demand stations.\n\nThis is not surprising: high-demand stations experience greater variability in trip counts, and a linear model has more room to be wrong in absolute terms where trip volumes are largest. Neighborhood stations with lower baseline demand tend to have lower MAE because they're easier to predict (most hours see zero or one trip).\n\nThe spatial pattern also suggests that missing features with spatial variation—such as proximity to transit hubs, office density, or tourist attractions—may be driving systematic underprediction in central areas.\n\n## Temporal Error Patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# MAE by time of day and day type \ntemporal_errors <- test_b %>%   \n  group_by(time_of_day, weekend) %>%   \n  summarize(     \n    MAE = mean(abs_error, na.rm = TRUE),     \n    .groups = \"drop\"   \n    ) %>%   \n  mutate(day_type = ifelse(weekend == 1, \"Weekend\", \"Weekday\"))  \n\nggplot(temporal_errors, aes(x = time_of_day, y = MAE, fill = day_type))+ \n  geom_col(position = \"dodge\") +   \n  scale_fill_manual(values = c(\"Weekday\" = \"#08519c\", \"Weekend\" = \"#6baed6\")) +   \n  labs(     \n    title = \"Prediction Errors by Time Period\",     \n    subtitle = \"When is the model struggling most?\",     \n    x = \"Time of Day\",     \n    y = \"Mean Absolute Error (trips)\",     \n    fill = \"Day Type\"   \n  ) +   \n  plotTheme +   \n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/temporal_errors-1.png){width=672}\n:::\n:::\n\n\nThe model struggles most during **PM Rush hours** (MAE \\~1.22 on weekdays, \\~1.15 on weekends), the highest errors of any time period.\n\nAM Rush on weekdays is also problematic (\\~1.02), but notably the weekend AM Rush error is much lower (\\~0.73), confirming that the model's difficulty is tied to commuter demand spikes it can't fully capture.\n\nCounterintuitively, **weekend Mid-Day errors (\\~1.05) exceed weekday Mid-Day (\\~0.85)**, suggesting that leisure demand in the middle of the day is harder to predict than structured weekday patterns. Overnight is by far the easiest period to predict (\\~0.30), reflecting the near-zero, highly stable demand.\n\n## Errors and Demographics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join demographic data to station errors \n\nstation_errors_demo <- station_errors %>%   \n  left_join(     \n    station_attributes_3 %>% \n      select(start_station, Med_Inc, Percent_Taking_Transit, Percent_White),\n    by = \"start_station\"   ) %>%   \n  filter(!is.na(Med_Inc))  \n\n# Create plots \n\np1 <- ggplot(station_errors_demo, aes(x = Med_Inc, y = MAE)) +   \n  geom_point(alpha = 0.5, color = \"#3182bd\") +   \n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +   \n  scale_x_continuous(labels = scales::dollar) +   \n  labs(title = \"Errors vs. Median Income\", x = \"Median Income\", y = \"MAE\") +   plotTheme  \n\np2 <- ggplot(station_errors_demo, aes(x = Percent_Taking_Transit, y = MAE)) +   geom_point(alpha = 0.5, color = \"#3182bd\") +   \n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +   \n  labs(title = \"Errors vs. Transit Usage\", x = \"% Taking Transit\", y = \"MAE\") +   \n  plotTheme  \n\np3 <- ggplot(station_errors_demo, aes(x = Percent_White, y = MAE)) +\n  geom_point(alpha = 0.5, color = \"#3182bd\") +   \n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +   \n  labs(title = \"Errors vs. Race\", x = \"% White\", y = \"MAE\") +   \n  plotTheme  \n\n(p1 | p2) / (p3 | plot_spacer())\n```\n\n::: {.cell-output-display}\n![](lab_5_files/figure-html/errors_demographics-1.png){width=672}\n:::\n:::\n\n\nAll three plots show consistent directional relationships. MAE increases with median income and % White, and decreases with transit usage—and the transit usage relationship is the strongest of the three.\n\nThe most straightforward interpretation is that high-income, predominantly white neighborhoods tend to have busier Indego stations with more volatile demand, producing larger absolute errors.\n\nThe equity implications are nuanced but serious. In lower-income, high-transit-dependency neighborhoods, Indego stations may be systematically *underpredicted* during the occasional high-demand events that do occur, meaning rebalancing resources may not reach those stations when needed. If the bike rebalancing algorithm relies on these predictions, it could mean that bikes are disproportionately allocated to already well-served Center City stations, while lower-income neighborhoods experience supply shortfalls. The higher `Percent_White` coefficient being positive in the model also suggests that predominantly white neighborhoods see higher predicted demand — a structural pattern in the data that reflects existing inequities in bike share station placement and usage, which the model will reproduce rather than correct\n\n# Part 3: Feature Engineering & model improvement\n\n### Spatial Features\n\n**Center City**\n\nA binary indicator for whether a station falls within a bounding box approximating Center City Philadelphia (\\~75.18°W to 75.14°W, 39.94°N to 39.97°N). The spatial error analysis showed that Center City stations have disproportionately high prediction errors, likely because they experience more extreme demand spikes tied to events, commuting density, and tourism. Adding a `center_city × rush_hour` interaction allows the model to apply a separate rush hour effect for these stations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Converting each station to a point for each row \nstations_sf <- study_panel_complete_3 %>%\n  distinct(start_station, start_lon, start_lat) %>%\n  st_as_sf(coords = c(\"start_lon\", \"start_lat\"), crs = 4326)\n\n# Defining Center City area through coordinates\ncenter_bbox <- st_bbox(c(\n  xmin = -75.18,\n  xmax = -75.14,\n  ymin = 39.94,\n  ymax = 39.97\n), crs = st_crs(4326))\n\n#turning it into polygon geometry\ncenter_polygon <- st_as_sfc(center_bbox)\n\n# this finds out each start station that falls within center city and assigns it a value of 1 \nstations_sf$center_city <- as.integer(st_within(stations_sf, center_polygon, sparse = FALSE))\n\n# Join back\nstudy_panel_complete_3 <- study_panel_complete_3 %>%\n  left_join(stations_sf %>% st_drop_geometry(), by = \"start_station\")\n```\n:::\n\n\n### Weather\n\n1.  **`feels_like`** (weather): A simplified heat index replacing raw temperature for observations above 80°F. In Q3, temperatures frequently exceeded 80°F; a 90°F day feels very different at 20% vs. 80% humidity, and the perceived temperature better captures the deterrent effect of heat on cycling. This replaces `Temperature` in the new model.\n\n2.  **`perfect_bike_weather`** (weather): A binary indicator for hours where temperature is between 65–80°F and there is no precipitation, conditions where cyclists are most likely to choose biking over other modes. This captures a non-linear \"sweet spot\" effect that a continuous temperature variable cannot express.\n\n3.  **`heavy_rain`** (weather): A binary indicator for precipitation \\> 0.05 inches/hour. Light rain may deter some riders, but heavy rain deters nearly all discretionary trips. Separating intensity levels provides more nuance than the raw precipitation variable alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Adding feels-like temperature (heat index for summer)\n# Heat index formula (NWS simplified) applies when Temp >= 80°F\n# Below 80°F, feels-like ≈ actual temperature\n\nstudy_panel_complete_3 <- study_panel_complete_3 %>%\n  mutate(\n    # Heat index (simplified Rothfusz equation for high temps)\n    feels_like = case_when(\n      Temperature >= 80 ~ -42.379 + \n                          2.04901523 * Temperature + \n                          10.14333127 * 50 +   # using avg summer humidity ~50%\n                          -0.22475541 * Temperature * 50 +\n                          -0.00683783 * Temperature^2 +\n                          -0.05481717 * 50^2 +\n                          0.00122874 * Temperature^2 * 50 +\n                          0.00085282 * Temperature * 50^2 +\n                          -0.00000199 * Temperature^2 * 50^2,\n      TRUE ~ Temperature\n    ),\n    # \"Perfect biking weather\" indicator: 65-80°F, no rain\n    perfect_bike_weather = as.integer(\n      Temperature >= 65 & Temperature <= 80 & Precipitation == 0\n    ),\n    # Heavy rain indicator\n    heavy_rain = as.integer(Precipitation > 0.05)\n  )\n```\n:::\n\n\n## NEW MODEL\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Update train and test sets with new features\ntrain_b <- study_panel_complete_3 %>%\n  filter(week >= 26 & week <= 35) %>%\n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\",\"Tue\",\"Wed\",\"Thu\",\"Fri\",\"Sat\",\"Sun\")))\ncontrasts(train_b$dotw_simple) <- contr.treatment(7)\n\ntest_b_new <- study_panel_complete_3 %>%\n  filter(week >= 36 & week <= 39) %>%\n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\",\"Tue\",\"Wed\",\"Thu\",\"Fri\",\"Sat\",\"Sun\")))\ncontrasts(test_b_new$dotw_simple) <- contr.treatment(7)\n\n# Re-add lag columns (they're already in study_panel_complete_3)\ncat(\"New features added: feels_like, perfect_bike_weather, heavy_rain\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNew features added: feels_like, perfect_bike_weather, heavy_rain\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(train_b %>% select(feels_like, perfect_bike_weather, heavy_rain))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   feels_like    perfect_bike_weather   heavy_rain      \n Min.   : 58.0   Min.   :0.0000       Min.   :0.000000  \n 1st Qu.: 72.0   1st Qu.:0.0000       1st Qu.:0.000000  \n Median : 77.0   Median :1.0000       Median :0.000000  \n Mean   : 78.4   Mean   :0.5628       Mean   :0.001984  \n 3rd Qu.: 83.9   3rd Qu.:1.0000       3rd Qu.:0.000000  \n Max.   :112.8   Max.   :1.0000       Max.   :1.000000  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 6: Best model (5) + spatial features + enhanced weather\n# Features added:\n#   - center_city: whether the station is in Center City (spatial)\n#   - feels_like: heat index temperature (weather)\n#   - perfect_bike_weather: indicator for ideal cycling conditions (weather)\n#   - heavy_rain: indicator for significant precipitation (weather)\n\nmodel6_b <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + \n    feels_like + Precipitation + heavy_rain + perfect_bike_weather +\n    lag1Hour + lag3Hours + lag1day + \n    rush_hour + as.factor(month) +\n    Med_Inc + Percent_Taking_Transit + Percent_White +\n    as.factor(start_station) +\n    rush_hour * weekend +\n    center_city * rush_hour,   # Rush hour effects especially strong in Center City\n  data = train_b\n)\n\ncat(\"Model 6 R-squared:\", summary(model6_b)$r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 6 R-squared: 0.3667433 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 6 Adj R-squared:\", summary(model6_b)$adj.r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 6 Adj R-squared: 0.366262 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Also try a Poisson model for count data\nmodel6_poisson <- glm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + \n    feels_like + Precipitation + heavy_rain + perfect_bike_weather +\n    lag1Hour + lag3Hours + lag1day +\n    rush_hour + as.factor(month) +\n    Med_Inc + Percent_Taking_Transit + Percent_White +\n    rush_hour * weekend +\n    center_city * rush_hour,\n  data = train_b,\n  family = poisson(link = \"log\")\n)\n\ncat(\"\\nPoisson Model AIC:\", AIC(model6_poisson), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPoisson Model AIC: 813240.7 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"OLS Model AIC:\", AIC(model6_b), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS Model AIC: 1174642 \n```\n\n\n:::\n:::\n\n\n### MAE\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate predictions from new models on the updated test set\n# Need to re-add error columns from Model 2 for baseline comparison\ntest_b_new <- test_b_new %>%\n  mutate(\n    pred2_new = predict(model2_b, newdata = test_b_new),\n    pred5_new = predict(model5_b, newdata = test_b_new),\n    pred6_ols = predict(model6_b, newdata = test_b_new),\n    pred6_pois = predict(model6_poisson, newdata = test_b_new, type = \"response\")\n  )\n\nmae_comparison <- data.frame(\n  Model = c(\n    \"2. Temporal Lags (baseline)\",\n    \"5. + Rush Hour Interaction\",\n    \"6. + Spatial + Weather Features (OLS)\",\n    \"6. + Spatial + Weather Features (Poisson)\"\n  ),\n  MAE = c(\n    mean(abs(test_b_new$Trip_Count - test_b_new$pred2_new), na.rm = TRUE),\n    mean(abs(test_b_new$Trip_Count - test_b_new$pred5_new), na.rm = TRUE),\n    mean(abs(test_b_new$Trip_Count - test_b_new$pred6_ols), na.rm = TRUE),\n    mean(abs(test_b_new$Trip_Count - test_b_new$pred6_pois), na.rm = TRUE)\n  )\n)\n\nkable(mae_comparison,\n      digits = 3,\n      caption = \"MAE Comparison: New Features vs. Prior Models\",\n      col.names = c(\"Model\", \"MAE (trips)\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>MAE Comparison: New Features vs. Prior Models</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> MAE (trips) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 2. Temporal Lags (baseline) </td>\n   <td style=\"text-align:right;\"> 0.748 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5. + Rush Hour Interaction </td>\n   <td style=\"text-align:right;\"> 0.740 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 6. + Spatial + Weather Features (OLS) </td>\n   <td style=\"text-align:right;\"> 0.737 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 6. + Spatial + Weather Features (Poisson) </td>\n   <td style=\"text-align:right;\"> 0.759 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nThe Poisson model is theoretically appropriate since `Trip_Count` is non-negative count data — OLS can predict negative counts, which is nonsensical. However, the results here are instructive: the Poisson model's MAE (0.759) is actually *worse* than the OLS Model 6 (0.737), and both are only marginal improvements over the simpler Model 2 baseline (0.748). The Poisson model achieves a much better AIC (813,241 vs. 1,174,642 for OLS), which reflects better distributional fit — but AIC and MAE are measuring different things. The temporal lag variables (lag1Hour, lag3Hours, lag1day) already do so much predictive heavy lifting that additional feature complexity yields diminishing returns. The new spatial and weather features together reduced MAE by about 0.011 trips relative to Model 2, a real but modest gain. In an operational context, these features would still be worth including since even small accuracy improvements at scale translate to fewer rebalancing errors across hundreds of stations.\n\n# Part 4: Q1 vs. Q3 Model Comparison\n\nThis lab trained and evaluated models exclusively on Q3 (July–September) Indego data. Extending predictions to Q1 (January–March) would require confronting a fundamentally different ridership regime. This section examines how and why the Q3 model would be expected to break down in winter, what retraining on Q1 data would likely reveal, and what the seasonal contrast implies for year-round deployment.\n\n## Seasonal Demand Differences\n\nThe most immediate challenge is scale. Q3 represents Indego's peak season: warm temperatures, long daylight hours, and high recreational and commuter ridership combine to produce system-wide trip counts roughly 2–3× higher than Q1. A Q3-trained model's intercept and coefficient magnitudes are calibrated to this higher baseline; applied to Q1 data, it would systematically overpredict trip counts at most stations. Beyond raw volume, the shape of demand differs. Q3 shows strong weekend recreational spikes — especially at waterfront and park-adjacent stations — that largely disappear in Q1, when ridership becomes more purely utilitarian. The temporal distribution also shifts: AM and PM rush peaks persist year-round but become a much larger share of total Q1 trips, while mid-day and evening leisure trips collapse. A model trained on Q3 would underweight rush-hour predictors relative to their importance in winter, and would assign too much predictive weight to weekend or afternoon indicators that carry little signal in Q1.\n\n## Model Transferability\n\nThe temporal lag variables — `lag1Hour`, `lag3Hours`, and `lag1day` — are the strongest predictors in the Q3 model and would likely remain informative in Q1, since autocorrelation in ridership patterns persists across seasons. However, their magnitude would differ: Q1 lags are predicting from a lower baseline, so the absolute values of lag coefficients learned in Q3 would tend to overestimate Q1 counts. Weather features tell a more complex story. In Q3, temperature has a roughly positive but weakening relationship with ridership (very hot days suppress cycling, while mild ones boost it). In Q1, the relationship becomes strongly positive and more linear — every additional degree above freezing is associated with meaningfully higher ridership. Precipitation effects are more severe in winter, when rain is more likely to coincide with near-freezing temperatures, making a wet Q1 day far more suppressive than a wet Q3 day. A model that learned Q3 weather coefficients would systematically misread Q1 weather signals. Station fixed effects, by contrast, would transfer reasonably well: the rank ordering of stations by baseline demand is relatively stable across seasons, even if absolute counts differ.\n\n## Feature Behavior Across Seasons\n\nSeveral features engineered in Part 3 would behave differently in Q1. The neighborhood density and employment access spatial features would retain their directional effects (higher-density, higher-employment areas still generate more commuter trips), but the rush-hour interaction added in Model 5 would become more dominant in Q1 — the interaction between `isRushHour` and station type captures the shift toward utilitarian ridership. The precipitation indicator would need recalibration; in Q3, a binary rain flag is roughly sufficient, but Q1 would benefit from distinguishing rain from snow/ice, which are far more suppressive. University proximity effects would also shift: Q1 includes the spring semester (starting mid-January), which generates more consistent ridership than Q3's early-semester period (late August onward), though break periods in January and March introduce demand gaps that the Q3 model has no analog for.\n\n## Implications for Deployment\n\nA single model trained on Q3 and applied year-round would perform well in summer and poorly in winter — exactly the wrong tradeoff if the goal is year-round rebalancing reliability. The most defensible deployment strategy is seasonal retraining: fit separate models on Q1 and Q3 data, transition between them at seasonal boundaries, and monitor MAE on holdout data as a leading indicator of when the active model is degrading. A pooled model with season-interaction terms (e.g., `Temperature × Q1Indicator`, `isWeekend × Q1Indicator`) offers a middle path that allows shared lag structure while permitting season-specific coefficients for weather and temporal features. Given the Part 4 Critical Reflection finding that the model already struggles with peak-hour volatility in Q3, Q1 deployment would require even more conservative operational thresholds — tighter confidence intervals, higher human-override triggers, and equity safeguards adjusted for the fact that Q1 low-income station demand is lower and thus even more likely to be deprioritized by a prediction-driven rebalancing algorithm.Part 4: Critical Reflection\n\n# Part 5: Critical Reflection\n\n**Operational Implications**\n\nThe best model achieves a test-set MAE of approximately 0.74 trips per station-hour. Whether this is “good enough” for Indego depends entirely on when and where errors occur. At the system average of \\~0.75 trips per station-hour, a MAE of 0.74 sounds deceptively precise — but the error analysis reveals that errors are highly concentrated in time and space. During PM Rush at busy Center City stations, the model can miss by 3–5 trips per hour, which is operationally significant: a station with 10 docks that is underpredicted by 4 trips may run empty before rebalancing crews arrive. The model would be most useful as one signal among many in a rebalancing decision system, rather than as a standalone automatic trigger. Deployment would be reasonable under conditions where (1) human operators retain override authority during peak hours, (2) the model is retrained seasonally to account for Q3-vs-Q1 demand differences, and (3) real-time corrections are applied using live dock availability data. Attempting to deploy a single model across all seasons without retraining would likely degrade performance significantly, given how differently summer and winter ridership patterns behave in Philadelphia.\n\n**Equity Considerations**\n\nThe demographic error analysis reveals a troubling pattern: prediction errors are systematically higher in higher-income, predominantly white neighborhoods — not because the model fails those communities, but because those neighborhoods have the busiest and most volatile stations. The inverse concern is more serious from an equity standpoint. Lower-income, high-transit-dependency neighborhoods have lower MAE largely because their stations see low, predictable demand — not because the model serves them well. If Indego’s rebalancing algorithm prioritizes stations where predicted demand is high and predictions are confident, it will consistently direct bikes toward wealthier neighborhoods and away from lower-income areas. This is a form of algorithmic feedback: the model learns from historical ridership patterns that already reflect unequal access, and then optimizes to serve the areas that already have the most bikes. Recommended safeguards include (1) equity-adjusted rebalancing targets that guarantee minimum bike availability at lower-income stations regardless of predicted demand, (2) regular auditing of rebalancing outcomes by neighborhood income and racial composition, and (3) supplementing prediction-based rebalancing with community engagement to surface demand that the historical data doesn’t capture.\n\n**Model Limitations**\n\nSeveral important patterns are likely missing from this model. First, it has no knowledge of special events — the Eagles game on September 4th showed that a single event can produce a 13% spike in citywide ridership, and the model would handle this as residual error. Second, the model treats station-hours as exchangeable once station fixed effects are removed, but in reality stations near universities (Penn, Drexel, Temple) exhibit very different seasonal patterns tied to the academic calendar, which began in late August during Q3. Third, the model assumes a stationary relationship between features and ridership — that a 75°F day in July triggers the same cycling response as a 75°F day in September, or that the same lag structure applies at midnight and at 5 PM. None of these assumptions perfectly hold. With more time, the most valuable additions would be: (1) a special events indicator linked to the Philadelphia events calendar; (2) university session indicators; (3) station-level dock capacity as a ceiling constraint on trip counts; and (4) a zero-inflated Poisson or negative binomial model to better handle the heavily right-skewed count distribution. Real-time data integration — live dock availability fed back into lag variables — would represent the most impactful single improvement for operational deployment.\n",
    "supporting": [
      "lab_5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}