<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Arzoo Gupta">

<title>Lab 4: Spatial Predictive Analysis – Arzoo Gupta - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Arzoo Gupta - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../Labs/Lab_0/lab0_template.html">
 <span class="dropdown-text">Lab 0</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Labs/Lab_1/lab1_template.html">
 <span class="dropdown-text">Lab 1: Census Data Quality for Policy Decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Labs/Lab_2/lab2_template.html">
 <span class="dropdown-text">Lab 2: Spatial Analysis and Visualization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Labs/Mid_Term_Project/Brar_Ceruso_Gupta_Satyal_March_17_Appendix.html">
 <span class="dropdown-text">Midterm Project: Predicted Model for Home Sales Price</span></a>
  </li>  
        <li class="dropdown-header">Midterm Project: Predicted Model for Home Sales Price</li>
        <li>
    <a class="dropdown-item" href="../../Labs/Lab_4/Lab_4.html">
 <span class="dropdown-text">Lab 4: Spatial Predictive Analysis; A Critical Examination of Predictive Policing Models</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-note-on-predictive-policing" id="toc-a-note-on-predictive-policing" class="nav-link active" data-scroll-target="#a-note-on-predictive-policing"><strong>A note on predictive policing:</strong></a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exploratory-data-analysis-for-broken-alley-lights" id="toc-exploratory-data-analysis-for-broken-alley-lights" class="nav-link" data-scroll-target="#exploratory-data-analysis-for-broken-alley-lights">Exploratory Data Analysis for Broken Alley Lights</a>
  <ul class="collapse">
  <li><a href="#part-1-data-loading-exploration" id="toc-part-1-data-loading-exploration" class="nav-link" data-scroll-target="#part-1-data-loading-exploration">Part 1: Data Loading &amp; Exploration</a></li>
  <li><a href="#part-2-fishnet-grid-creation" id="toc-part-2-fishnet-grid-creation" class="nav-link" data-scroll-target="#part-2-fishnet-grid-creation">Part 2: Fishnet Grid Creation</a></li>
  <li><a href="#part-3-spatial-features" id="toc-part-3-spatial-features" class="nav-link" data-scroll-target="#part-3-spatial-features">Part 3: Spatial Features</a></li>
  <li><a href="#part-4-loading-burglary-data" id="toc-part-4-loading-burglary-data" class="nav-link" data-scroll-target="#part-4-loading-burglary-data">Part 4: Loading Burglary Data</a></li>
  <li><a href="#part-5-kde-baseline" id="toc-part-5-kde-baseline" class="nav-link" data-scroll-target="#part-5-kde-baseline">Part 5: KDE Baseline</a></li>
  <li><a href="#part-6-count-regression-models" id="toc-part-6-count-regression-models" class="nav-link" data-scroll-target="#part-6-count-regression-models">Part 6: Count Regression Models</a></li>
  <li><a href="#part-7-spatial-cross-validation-2017" id="toc-part-7-spatial-cross-validation-2017" class="nav-link" data-scroll-target="#part-7-spatial-cross-validation-2017">Part 7: Spatial Cross-Validation (2017)</a></li>
  <li><a href="#part-8-model-evaluation" id="toc-part-8-model-evaluation" class="nav-link" data-scroll-target="#part-8-model-evaluation">Part 8: Model Evaluation</a></li>
  <li><a href="#part-9-model-errors" id="toc-part-9-model-errors" class="nav-link" data-scroll-target="#part-9-model-errors">Part 9: Model Errors</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 4: Spatial Predictive Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Arzoo Gupta </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="a-note-on-predictive-policing" class="level2">
<h2 class="anchored" data-anchor-id="a-note-on-predictive-policing"><strong>A note on predictive policing:</strong></h2>
<p>This is an academic exercise conducted to understand the mechanics, and the limits, of spatial predictive modeling in a public safety context. Building a model that predicts crime risk is not the same as recommending that one be used, and this lab should be read in that spirit.</p>
<p>Chicago offers one of the most well-documented cautionary examples of what happens when predictive tools move from the classroom into deployment without sufficient scrutiny. It was a story about bad data, and the consent decree is where that becomes legally verifiable. The DOJ investigation that preceded the consent decree was triggered by the 2014 killing of Laquan McDonald. That investigation found that the Chicago Police Department routinely violated the constitutional rights of Black and Latinx residents, used excessive force, and operated with a culture of impunity, and that officers commonly stopped and searched Black youth without legal justification, driven by racial stereotypes rather than reasonable suspicion. <a href="https://www.chicagoreporter.com/six-years-23-percent-chicagos-failed-promise-of-police-reform/"><u>The Chicago Reporter</u></a> The Illinois Attorney General filed a lawsuit in August 2017 to force a consent decree, and it took effect in January 2019. <a href="https://www.chicagopoliceconsentdecree.org/about/"><u>Chicagopoliceconsentdecree</u></a></p>
<p>This is where a landmark 2019 report by the AI Now Institute becomes directly relevant. The researchers examined 13 jurisdictions that had used predictive policing systems and cross-referenced them with consent decrees and federal court-monitored settlements; using those legal findings as proof that unconstitutional policing practices had shaped the underlying data. Chicago was their first case study: a documented example of a jurisdiction where dirty data was ingested directly into the city’s predictive policing system. <a href="https://www.nyulawreview.org/wp-content/uploads/2019/04/NYULawReview-94-Richardson-Schultz-Crawford.pdf"><u>NYULawReview</u></a> The concept they introduced, “dirty data,” refers to data derived from or influenced by corrupt, biased, and unlawful practices, including both discriminatory policing and manipulation of crime statistics. The consent decree provided the legally verified paper trail proving that this is exactly what happened in Chicago.</p>
<p>This matters for the analysis that follows. The burglary data used in this lab was generated by a police department that was simultaneously under federal scrutiny for unconstitutional practices. Any model trained on that data does not neutrally describe where crime occurs, it describes where a constitutionally non-compliant police department directed its attention and made its arrests.</p>
<p>After six years of federal oversight and more than $15 million spent on independent monitoring, CPD has fully implemented just 23 percent of the reforms it agreed to. <a href="https://www.chicagoreporter.com/six-years-23-percent-chicagos-failed-promise-of-police-reform/"><u>The Chicago Reporter</u></a> The data being generated today is still produced by an institution mid-reform at best. What follows is an exercise in understanding how spatial predictive models are constructed, offered precisely so we can think critically about why they should never be deployed uncritically, and why Chicago’s experience is not an anomaly but a warning.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>When alley lights go out, they don’t just create inconvenience; they create voids of darkness in spaces that already lack foot traffic and natural surveillance. This analysis examines 311 reports of broken alley lights in Chicago during 2017 to ask a spatial question: can the geographic distribution of infrastructure neglect — specifically, unlit alleys — help predict where burglaries occur?</p>
<p>But before proceeding, it is worth naming what this kind of analysis does and does not do. Mapping broken alley lights and burglaries together does not reveal causation — it reveals correlation.</p>
<p>Using 311 data as a predictor of crime risk means using a signal that is itself shaped by who calls 311, how quickly complaints are resolved, and which neighborhoods receive timely responses. A model trained on this data doesn’t neutrally describe reality. That is the data problem at the heart of any predictive policing application, and it is why we build this model to understand.</p>
<p>The neighborhoods with the most broken light complaints are also the neighborhoods that could have:</p>
<ol type="1">
<li>Historically been under-resourced, over-policed, and subject to discriminatory city services.</li>
<li>Have an active community that has found the 311 service reliable.</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>✓ All packages loaded successfully!</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>✓ Working directory: C:/Users/arzoo/OneDrive - PennO365/Documents/GitHub/PPA-Portfolio/Labs/Lab_4 </code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis-for-broken-alley-lights" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-for-broken-alley-lights">Exploratory Data Analysis for Broken Alley Lights</h2>
<section id="part-1-data-loading-exploration" class="level3">
<h3 class="anchored" data-anchor-id="part-1-data-loading-exploration">Part 1: Data Loading &amp; Exploration</h3>
<p>The 311 violation data for broken alley lights have been loaded into the R environment. Along with this Police Beats, Districts, and the Chicago Boundary have been using API’s from the city of Chicago’s data portal. The data has been subsequently cleaned for further analysis. It has also been projected into the Chicago 1983 NAD state-plane to ensure spatial accuracy in future calculations.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>✓ Cleaned Alley Lights Violation Data</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Violations: 27890 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Date range: 2017/01/01 to 2017/12/31 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>✓ Loaded spatial boundaries</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Police districts: 25 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Police beats: 277 </code></pre>
</div>
</div>
<section id="choropleth-map-of-all-non-functioning-alley-lights-311-calls" class="level4">
<h4 class="anchored" data-anchor-id="choropleth-map-of-all-non-functioning-alley-lights-311-calls">Choropleth Map of all non-functioning alley lights 311 calls</h4>
<p>The dot map below reveals something more important than the total count: these complaints are not evenly distributed. Large swaths of the North Side and the lakefront appear relatively sparse, while the West Side and parts of the South Side are so densely covered in dots that individual points are nearly indistinguishable. This is not a map of broken lights, it is a map of where broken lights are reported, where residents engage with city services.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bar-charts-for-311-calls" class="level4">
<h4 class="anchored" data-anchor-id="bar-charts-for-311-calls">Bar Charts for 311 calls</h4>
<p>The monthly bar chart complicates this further. Rather than peaking in summer, complaints are actually highest in January, February, and March—the winter months—and notably lower through July and August. This is counterintuitive if we think of 311 calls as a direct response to dangerous darkness. It may instead reflect patterns of indoor activity in winter leading people to notice alley lights from windows, or seasonal city maintenance cycles. Whatever the cause, the seasonality is a reminder that 311 data is a record of human behavior around reporting, not a direct sensor reading of infrastructure failure.</p>
<p>The resolution time histogram drives this point home sharply. The distribution is heavily right-skewed: the vast majority of complaints are resolved within a few days, creating the tall spike at the left of the histogram, but a long tail extends far to the right—some complaints take months to close. This variance in response time is not random. It is spatially structured, as the district-level maps below reveal.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/EDA-Violation-Data-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/EDA-Violation-Data-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="choropleth-maps-of-resolution-time-and-multiple-complaints" class="level4">
<h4 class="anchored" data-anchor-id="choropleth-maps-of-resolution-time-and-multiple-complaints">Choropleth Maps of Resolution Time and Multiple Complaints</h4>
<p>The left district map shows average resolution time by police district. The differences are substantial with some districts resolve complaints in under three weeks on average while others stretch past 60 days.</p>
<p>The right map shows the duplicate complaint rate: the share of 311 calls flagged as duplicates, meaning another resident already reported the same broken light. Districts with the highest duplicate rates, reaching 40–50% in some areas, are places where lights stay broken long enough for multiple residents to independently call it in. Together these two maps document something the aggregate count hides: the city’s response to broken alley lights is deeply unequal, and that inequality follows the same geography as Chicago’s broader patterns of disinvestment. The districts that wait longest for repairs and generate the most duplicate complaints are the same neighborhoods that will show up later in this analysis as burglary hot spots. That is not a coincidence, it is a structural condition that any model trained on this data will absorb and reproduce.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/comparing-violations-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="part-2-fishnet-grid-creation" class="level3">
<h3 class="anchored" data-anchor-id="part-2-fishnet-grid-creation">Part 2: Fishnet Grid Creation</h3>
<p>Rather than analyzing violations as individual points, we aggregate them into a regular grid of 500-meter by 500-meter cells covering the entire city. This fishnet approach converts Chicago into a set of consistently-sized units of analysis compatible with regression modeling. Instead of asking “how many lights are broken near this address,” we can ask “how many lights are broken in each cell” a format that allows us to attach predictors and outcomes to the same spatial unit and estimate a statistical relationship between them.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>✓ Created fishnet grid</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Number of cells: 2458 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Cell size: 500 x 500 meters</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Cell area: 250000 square meters</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Broken Light distribution:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    1.00    7.00   11.35   17.00  217.00 </code></pre>
</div>
</div>
<p>The fishnet map of broken alley light counts reveals a pattern that the dense dot map above obscured. Most of the city’s cells contain relatively few complaints—the map is predominantly dark purple—but a handful of cells, particularly in clusters on the West Side, register counts approaching or exceeding 200. These extreme cells are not randomly distributed; they sit in recognizable corridors of the city that correspond to areas with the longest resolution times and highest duplicate complaint rates we saw in the district maps. The fishnet makes this structure legible for modeling in a way the point map could not.</p>
<p>t also makes a quiet data quality problem visible. The North Side and lakefront cells are almost uniformly dark, near-zero complaint counts, while structurally similar streets in other parts of the city register far more. This could reflect genuinely better infrastructure maintenance. Or it could reflect lower reporting rates, faster city response that resolves complaints before they accumulate, or simply less trust in 311 as a useful channel.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/fishnet-violation-viz-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="part-3-spatial-features" class="level3">
<h3 class="anchored" data-anchor-id="part-3-spatial-features">Part 3: Spatial Features</h3>
<section id="k-nearest-neighbours" class="level4">
<h4 class="anchored" data-anchor-id="k-nearest-neighbours">K-Nearest Neighbours</h4>
<p>A single count of broken lights in each cell captures local conditions but misses the spatial context surrounding that cell. A grid cell with zero complaints is not necessarily a well-lit area, it may simply be a place where the reporting behavior or response times we documented above result in fewer recorded complaints. To capture proximity to known infrastructure failures regardless of what happens to be recorded in any individual cell, we calculate the mean distance from each cell’s centroid to its three nearest broken light complaints. A small value means the cell sits close to documented failures; a large value means it is relatively isolated from them. This feature allows the model to borrow spatial information from neighboring areas and is particularly important for smoothing over the reporting-behavior noise that makes the raw counts unreliable in some parts of the city.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>✓ Calculated nearest neighbor distances</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
   4.602  102.009  172.653  295.489  328.127 2313.532 </code></pre>
</div>
</div>
</section>
<section id="local-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="local-morans-i">Local Moran’s I</h4>
<p>Local Moran’s I is a measure of spatial autocorrelation. It asks whether a cell’s value is similar to or different from its neighbors in a way that is statistically unlikely to occur by chance. Applied here to the broken alley lights count, it classifies each cell into a cluster type.</p>
<p>The resulting map is interesting. Rather than a broad wash of hot spots across the South and West sides, the High-High cells, places where many broken lights are surrounded by more broken lights, appear as a series of tight, discrete clusters scattered along a north-south corridor through the middle of the city, with additional clusters on the West Side. The vast majority of the city, including most of the North Side and far South Side, is classified as not significant.</p>
<p>This spottiness is itself informative. It tells us that infrastructure neglect as captured by 311 data is not a smooth citywide gradient but a pattern of localized clusters, specific corridors and intersections where failures accumulate and persist. It also tells us that the relationship between broken lights and the underlying conditions we are trying to capture is more spatially concentrated than a simple choropleth of complaint counts would suggest. These hot spots will become a key predictive feature: whether a cell sits near one of these clusters of persistent failure is a meaningful signal about the environmental conditions in that area.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/morans-viz-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="distance-to-hotspots" class="level4">
<h4 class="anchored" data-anchor-id="distance-to-hotspots">Distance to Hotspots</h4>
<p>Using the High-High clusters identified above, we calculate the Euclidean distance from each grid cell to the nearest broken lights hot spot. This converts the cluster map into a continuous feature: cells within or immediately adjacent to a hot spot get near-zero values, while cells far from any significant cluster get large values. It is a concise summary of how embedded each cell is in a zone of systemic infrastructure neglect, and it is the spatial feature most likely to carry predictive power across the full fishnet even in cells that have few direct complaints of their own.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>✓ Calculated distance to broken alley lights hot spots
  - Number of hot spot cells: 193 </code></pre>
</div>
</div>
</section>
</section>
<section id="part-4-loading-burglary-data" class="level3">
<h3 class="anchored" data-anchor-id="part-4-loading-burglary-data">Part 4: Loading Burglary Data</h3>
<p>With the infrastructure features in place, we can now load the outcome variable: 2017 burglary incidents recorded by the Chicago Police Department. These 7,482 reported burglaries are joined to the fishnet grid using a spatial join, so each cell receives a count of how many burglaries occurred within its boundaries.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
✓ Loaded burglary data</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Number of burglaries: 7482 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - CRS: ESRI:102271 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Date range: 2017-01-01 to 2018-01-01 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/burglary-data-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Map A shows the raw point locations of all 7,482 burglaries recorded in Chicago in 2017. The distribution is not uniform: the North Side and the lakefront corridor are noticeably sparse, while a dense band running through the West Side and portions of the South Side concentrates the bulk of incidents. The far south and northwest corners of the city are relatively quiet. What the dot map cannot easily convey, however, is the difference between a cluster of 10 incidents and a cluster of 40 — at this density, the eye can only register “many” or “few.”</p>
<p>Map B translates that point cloud into a continuous density surface using density estimation. The structure that was visually implied by the dots becomes much clearer here. There are three distinct high-density peaks: one on the upper West Side, and two on the South Side separated by a corridor of lower activity. These are not smoothed-out noise, they are real concentrations of reported burglary risk that the KDE bandwidth has revealed by borrowing signal from neighboring points. The yellow areas at the city’s edges and the North Side represent near-baseline risk by comparison.</p>
<p>Together, these two panels establish what the model is trying to predict and where the hardest prediction problem lies. The dense cores visible in Map B are precisely the areas where the model’s errors will be largest—where burglary risk is driven by deeply structural conditions that broken alley light data can only partially proxy.</p>
<section id="fishnet-with-burglary-data" class="level4">
<h4 class="anchored" data-anchor-id="fishnet-with-burglary-data">Fishnet With Burglary Data</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Burglary count distribution:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   2.000   3.042   5.000  40.000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Cells with zero burglaries: 781 / 2458 ( 31.8 %)</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/comparing-burglary-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The resulting distribution is heavily right-skewed. The median cell contains just 2 burglaries, but the maximum reaches 40, and nearly a third of all cells— 31.8%—contain zero burglaries entirely. This zero-inflation is one of the core statistical challenges this model must address, and it is why a count regression approach is more appropriate than ordinary linear regression here. A normal distribution simply does not describe data shaped like this.</p>
</section>
</section>
<section id="part-5-kde-baseline" class="level3">
<h3 class="anchored" data-anchor-id="part-5-kde-baseline">Part 5: KDE Baseline</h3>
<p>Before fitting a regression model, we establish a Kernel Density Estimation (KDE) baseline, a purely data-driven smoothing of the 2017 burglary points into a continuous risk surface. KDE doesn’t use any predictors; it simply asks where burglaries were concentrated and spreads that signal outward using a bandwidth-determined decay function.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>✓ Calculated KDE baseline</code></pre>
</div>
</div>
<p>The KDE map serves two purposes. First, it gives us a visual reference for the geographic structure of burglary risk that the regression model will need to approximate or improve upon. Second, it provides a formal performance benchmark: at the end of this analysis, we can ask whether a model that incorporates broken alley light features actually outperforms a method that uses only the spatial distribution of past crime.</p>
<p>The side-by-side comparison of the violation data and the KDE surface is instructive. The broken light clusters and the burglary density surface share substantial geographic overlap, particularly in the corridors through the West Side, but they are not identical. There are pockets of high burglary density with relatively few broken light complaints, and vice versa. The model will need to capture the shared signal while not being misled by the divergences.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/kde-viz-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<section id="comparing-311-calls-and-burglaries-in-2017" class="level4">
<h4 class="anchored" data-anchor-id="comparing-311-calls-and-burglaries-in-2017">Comparing 311 Calls and Burglaries in 2017</h4>
<p>Placing the two fishnet maps side by side makes the central question of this analysis visual: do broken alley lights and burglaries cluster in the same places? The answer is largely yes, but with important nuance.</p>
<p>The left map shows broken alley light 311 complaints aggregated to the 500-meter fishnet. The brightest cells—reaching counts above 200—are concentrated in a corridor running through the West Side, with secondary clusters on the South Side. The North Side and lakefront are predominantly dark purple, near zero.</p>
<p>The right map shows 2017 burglary counts on the same grid. The scale is much smaller (maxing at 40 rather than 200), but the spatial pattern rhymes closely with the left. The West Side corridor lights up again, and the South Side clusters reappear in roughly the same locations. The North Side remains comparatively quiet.</p>
<p>But the maps are not identical, and the differences matter as much as the similarities. There are cells with high broken light counts but moderate burglary counts, and a few cells—particularly on the far South Side—where burglaries concentrate without a corresponding spike in light complaints. Areas with low complaint counts may have poor lighting and high crime that simply isn’t being reported through that channel. The model that follows attempts to extract signal from the shared geography while acknowledging that the two patterns are correlated proxies, not the same thing.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/comparing-violation-burglary-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>✓ Joined police districts</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Districts: 22 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Cells: 1708 </code></pre>
</div>
</div>
</section>
</section>
<section id="part-6-count-regression-models" class="level3">
<h3 class="anchored" data-anchor-id="part-6-count-regression-models">Part 6: Count Regression Models</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>✓ Prepared modeling data</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Observations: 1708 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  - Variables: 6 </code></pre>
</div>
</div>
<section id="poisson-regression" class="level4">
<h4 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h4>
<p>We fit two count regression models to explain burglary counts per fishnet cell using three predictors: the raw count of broken alley light complaints in each cell (<code>lights_out_2017</code>), the mean distance to the three nearest light complaints (<code>lights_out.nn</code>), and the distance to the nearest spatial hot spot cluster (<code>dist_to_hotspot</code>).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = countBurglaries ~ lights_out_2017 + lights_out.nn + 
    dist_to_hotspot, family = "poisson", data = fishnet_model)

Coefficients:
                   Estimate  Std. Error z value             Pr(&gt;|z|)    
(Intercept)      1.94834912  0.03567900  54.608 &lt; 0.0000000000000002 ***
lights_out_2017  0.00272317  0.00078882   3.452             0.000556 ***
lights_out.nn   -0.00338524  0.00014444 -23.437 &lt; 0.0000000000000002 ***
dist_to_hotspot -0.00010389  0.00001058  -9.822 &lt; 0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 6710.3  on 1707  degrees of freedom
Residual deviance: 4963.8  on 1704  degrees of freedom
AIC: 9032.2

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>The first model is a Poisson regression, which is the standard starting point for count data. All three predictors are highly significant. More broken lights in a cell is positively associated with burglary counts; greater distance from complaints and hot spots is negatively associated, as expected.</p>
</section>
<section id="checking-for-dispersion" class="level4">
<h4 class="anchored" data-anchor-id="checking-for-dispersion">Checking for Dispersion</h4>
<p>However, the dispersion test reveals a dispersion parameter of 3.25, well above the rule-of-thumb threshold of 1.5, indicating that the Poisson model’s assumption of equal mean and variance is violated. The data is overdispersed, meaning there is more variability in the burglary counts than Poisson can accommodate.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Dispersion parameter: 3.25 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Rule of thumb: &gt;1.5 suggests overdispersion</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>⚠ Overdispersion detected! Consider Negative Binomial model.</code></pre>
</div>
</div>
</section>
<section id="negative-binomial-model" class="level4">
<h4 class="anchored" data-anchor-id="negative-binomial-model">Negative Binomial Model</h4>
<p>The Negative Binomial model addresses this by estimating a separate dispersion parameter (θ = 1.655). The improvement in fit is substantial: AIC drops from 9,032 (Poisson) to 7,557 (Negative Binomial), and the residual deviance falls from 4,964 to 1,861. The coefficient signs and significance patterns are consistent across both models, which gives confidence that the relationships are real and not artifacts of distributional misspecification. We proceed with the Negative Binomial model for all subsequent steps.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = countBurglaries ~ lights_out_2017 + lights_out.nn + 
    dist_to_hotspot, data = fishnet_model, init.theta = 1.654963477, 
    link = log)

Coefficients:
                   Estimate  Std. Error z value             Pr(&gt;|z|)    
(Intercept)      1.95361263  0.06651523  29.371 &lt; 0.0000000000000002 ***
lights_out_2017  0.00352497  0.00169544   2.079               0.0376 *  
lights_out.nn   -0.00361395  0.00021646 -16.696 &lt; 0.0000000000000002 ***
dist_to_hotspot -0.00009261  0.00001807  -5.125          0.000000298 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.655) family taken to be 1)

    Null deviance: 2576.7  on 1707  degrees of freedom
Residual deviance: 1861.1  on 1704  degrees of freedom
AIC: 7556.5

Number of Fisher Scoring iterations: 1

              Theta:  1.6550 
          Std. Err.:  0.0949 

 2 x log-likelihood:  -7546.4900 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Model Comparison:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Poisson AIC: 9032.2 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Negative Binomial AIC: 7556.5 </code></pre>
</div>
</div>
</section>
</section>
<section id="part-7-spatial-cross-validation-2017" class="level3">
<h3 class="anchored" data-anchor-id="part-7-spatial-cross-validation-2017">Part 7: Spatial Cross-Validation (2017)</h3>
<p>Standard cross-validation randomly splits observations into training and test sets, which tends to be optimistic for spatial data because nearby cells share unmeasured characteristics. A model trained on cells adjacent to the test area has already “seen” the spatial context it is being asked to predict. Leave-One-Group-Out (LOGO) cross-validation corrects for this by holding out an entire geographic unit, here, a police district, at a time, training on the remaining 21 districts, and predicting the held-out one.</p>
<p>Across 22 folds, the model achieves a mean MAE of 2.57 burglaries per cell and a mean RMSE of 3.49. Performance varies considerably by district. District 3, produces the highest MAE at 5.87, the model struggles most where burglary counts are high and spatially concentrated in ways the alley light features don’t fully capture. Districts 17 and 20 on the Northwest Side produce the lowest errors, around 1.78–1.80, in areas where burglary rates are more moderate and the signal from broken light infrastructure is more spatially consistent.</p>
<p>This geographic variation in error is itself informative. The places the model predicts worst are places where either the broken light data is least reliable as a proxy for conditions, or where the structural drivers of burglary are not well-captured by infrastructure neglect alone.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Running LOGO Cross-Validation...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Fold 1 / 22 - District 5 - MAE: 1.95 
  Fold 2 / 22 - District 4 - MAE: 1.84 
  Fold 3 / 22 - District 22 - MAE: 2.4 
  Fold 4 / 22 - District 6 - MAE: 3.08 
  Fold 5 / 22 - District 8 - MAE: 3.24 
  Fold 6 / 22 - District 7 - MAE: 2.96 
  Fold 7 / 22 - District 3 - MAE: 5.87 
  Fold 8 / 22 - District 2 - MAE: 2.8 
  Fold 9 / 22 - District 9 - MAE: 2.03 
  Fold 10 / 22 - District 10 - MAE: 2.33 
  Fold 11 / 22 - District 1 - MAE: 2.34 
  Fold 12 / 22 - District 12 - MAE: 3.29 
  Fold 13 / 22 - District 15 - MAE: 1.88 
  Fold 14 / 22 - District 11 - MAE: 2.87 
  Fold 15 / 22 - District 18 - MAE: 2.39 
  Fold 16 / 22 - District 25 - MAE: 2.5 
  Fold 17 / 22 - District 14 - MAE: 2.75 
  Fold 18 / 22 - District 19 - MAE: 2.07 
  Fold 19 / 22 - District 16 - MAE: 2.38 
  Fold 20 / 22 - District 17 - MAE: 1.78 
  Fold 21 / 22 - District 20 - MAE: 1.8 
  Fold 22 / 22 - District 24 - MAE: 2.02 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
✓ Cross-Validation Complete</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean MAE: 2.57 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean RMSE: 3.49 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>LOGO CV Results by District</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">fold</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">test_district</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n_test</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mae</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rmse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">5.87</td>
<td style="text-align: right;">7.64</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: left;">12</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">3.29</td>
<td style="text-align: right;">4.74</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">197</td>
<td style="text-align: right;">3.24</td>
<td style="text-align: right;">4.20</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">6</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">3.08</td>
<td style="text-align: right;">4.52</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">2.96</td>
<td style="text-align: right;">3.85</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">2.87</td>
<td style="text-align: right;">3.51</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">2.80</td>
<td style="text-align: right;">3.53</td>
</tr>
<tr class="even">
<td style="text-align: right;">17</td>
<td style="text-align: left;">14</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">4.17</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16</td>
<td style="text-align: left;">25</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">3.45</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">22</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">2.40</td>
<td style="text-align: right;">2.89</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: left;">18</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">2.39</td>
<td style="text-align: right;">4.02</td>
</tr>
<tr class="even">
<td style="text-align: right;">19</td>
<td style="text-align: left;">16</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">2.38</td>
<td style="text-align: right;">2.82</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">2.34</td>
<td style="text-align: right;">3.20</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">10</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">2.33</td>
<td style="text-align: right;">3.18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18</td>
<td style="text-align: left;">19</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">2.07</td>
<td style="text-align: right;">2.65</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: left;">9</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">2.03</td>
<td style="text-align: right;">2.53</td>
</tr>
<tr class="odd">
<td style="text-align: right;">22</td>
<td style="text-align: left;">24</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">2.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">5</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">1.95</td>
<td style="text-align: right;">2.75</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: left;">15</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">2.40</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">235</td>
<td style="text-align: right;">1.84</td>
<td style="text-align: right;">3.48</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: left;">20</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">1.80</td>
<td style="text-align: right;">2.16</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: left;">17</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">2.17</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="part-8-model-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="part-8-model-evaluation">Part 8: Model Evaluation</h3>
<p>Comparing the regression model to the KDE baseline reveals a mixed picture. The KDE baseline achieves a lower MAE (2.06 vs.&nbsp;2.43) and lower RMSE (2.95 vs.&nbsp;3.49). By these headline accuracy metrics, the simpler method performs better on 2017 data.</p>
<p>This is not surprising and is worth interpreting carefully rather than treating as a failure of the regression approach. KDE is essentially a sophisticated spatial smoother that encodes where past crime occurred — it is almost guaranteed to fit historical patterns well. The regression model, by contrast, is attempting something harder: it is trying to explain burglary counts from upstream infrastructure conditions rather than simply recapitulating the crime distribution itself. A model that uses broken light features to predict burglaries is more interpretable, more actionable for policy purposes, and potentially more generalizable to new years or new geographies than a KDE surface built from historical crime alone.</p>
<p>The side-by-side map of predicted versus actual counts helps locate where the discrepancies are largest. The model tends to underpredict in the highest-burglary cells — a common pattern with count models when extreme values are rare and the right tail is difficult to capture — and to overpredict in some low-burglary areas with high broken light counts, reinforcing the earlier observation that broken lights and burglaries are correlated but not co-located everywhere.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/compare-models -viz-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Model Performance Comparison</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">approach</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mae</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rmse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">model</td>
<td style="text-align: right;">2.43</td>
<td style="text-align: right;">3.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">kde</td>
<td style="text-align: right;">2.06</td>
<td style="text-align: right;">2.95</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="part-9-model-errors" class="level3">
<h3 class="anchored" data-anchor-id="part-9-model-errors">Part 9: Model Errors</h3>
<p>The error maps make the spatial structure of model performance explicit. The model’s largest positive residuals, cells where actual burglaries far exceeded predictions, cluster on the West Side and in parts of the South Side, particularly in District 3. These are areas where burglary risk appears to be driven by factors beyond what broken alley light data can capture: concentrated poverty, housing vacancy, and patterns of police under-reporting that the 311 signal does not reflect.</p>
<p>The largest negative residuals, cells where the model predicted more burglaries than occurred, are scattered more evenly across the city, including some higher-income North Side neighborhoods with few broken lights and few burglaries but where the model’s proximity features still generate modest positive predictions.</p>
<p>The exponentiated coefficient table provides a final summary of the model’s learned relationships. Each additional broken light complaint in a cell is associated with a 0.4% increase in the expected burglary count (rate ratio = 1.004). Each additional meter of distance from the nearest complaint reduces expected burglaries by 0.4% (rate ratio = 0.996). Distance to hot spots shows a similarly small but statistically significant negative relationship. These effect sizes are modest, consistent with the idea that broken alley lights are one of many overlapping signals in a complex spatial system rather than a primary driver of burglary risk.</p>
<p>Taken together, the error analysis reinforces the broader critique in the introduction. The places this model gets wrong most severely are the same places where the underlying data, policing records generated by an institution under federal scrutiny for unconstitutional practices, is least likely to be an accurate representation of where crime actually occurs. Modeling error in this context is not just a technical problem; it is a trace of the structural inequities baked into the data from the start.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab_4_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Final Negative Binomial Model Coefficients (Exponentiated)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rate Ratio</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Z</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">7.054</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">29.371</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">lights_out_2017</td>
<td style="text-align: right;">1.004</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">2.079</td>
<td style="text-align: right;">0.038</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lights_out.nn</td>
<td style="text-align: right;">0.996</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-16.696</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">dist_to_hotspot</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-5.125</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Rate ratios &gt; 1 indicate positive association with burglary counts.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
<p>*(<strong>Claude Sonnet 4.6 was used to debug code)</strong></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>